(() => {
  const C=window.LATIH_CONFIG,E=window.LATIH_ENGINE;
  const app=document.querySelector('#app'),toastEl=document.querySelector('#toast'),loading=document.querySelector('#loading'),loadingTitle=document.querySelector('#loadingTitle'),loadingText=document.querySelector('#loadingText');
  const defaults={xp:0,streak:0,lastDay:'',sessions:[],answers:0,correct:0,settings:{sound:true,timer:false,offlineDownloadedAt:''},prefs:{level:'1',subject:'math',topic:'Campur Semua',mode:'learn',count:10,difficulty:'auto'}};
  let state=load(),view='home',quiz=null,installPrompt=null,timerInt=null;
  function clone(x){return JSON.parse(JSON.stringify(x))}
  function merge(a,b){const o=clone(a);for(const k in b){o[k]=(b[k]&&typeof b[k]==='object'&&!Array.isArray(b[k]))?merge(o[k]||{},b[k]):b[k]}return o}
  function load(){try{return merge(defaults,JSON.parse(localStorage.getItem('latihkuState')||'{}'))}catch{return clone(defaults)}}
  function save(){localStorage.setItem('latihkuState',JSON.stringify(state))}
  function esc(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
  function toast(m){toastEl.textContent=m;toastEl.classList.add('show');setTimeout(()=>toastEl.classList.remove('show'),2200)}
  function showLoading(title='Memuatkan…',text=''){loadingTitle.textContent=title;loadingText.textContent=text;loading.classList.remove('hidden')}
  function hideLoading(){loading.classList.add('hidden')}
  function dayKey(d=new Date()){return `${d.getFullYear()}-${d.getMonth()+1}-${d.getDate()}`}
  function updateStreak(){const t=dayKey();if(state.lastDay===t)return;const y=new Date();y.setDate(y.getDate()-1);state.streak=state.lastDay===dayKey(y)?state.streak+1:1;state.lastDay=t;save()}
  function levelObj(id=state.prefs.level){return C.levels.find(x=>x.id===id)||C.levels[1]}
  function subObj(id=state.prefs.subject){return C.subjects[id]||C.subjects.math}
  function iconSubject(id){return C.subjects[id]?.emoji||'📚'}
  function formatBytes(bytes){if(bytes<1024)return `${bytes} B`;if(bytes<1024**2)return `${(bytes/1024).toFixed(1)} KB`;return `${(bytes/1024**2).toFixed(1)} MB`}
  function beep(ok=true){if(!state.settings.sound)return;try{const A=window.AudioContext||window.webkitAudioContext;const ctx=new A(),osc=ctx.createOscillator(),gain=ctx.createGain();osc.type='sine';osc.frequency.value=ok?660:220;gain.gain.value=.035;osc.connect(gain);gain.connect(ctx.destination);osc.start();osc.stop(ctx.currentTime+.10);osc.onended=()=>ctx.close()}catch{}}
  function nav(active){return `<nav class="bottomnav">${[['home','🏠','Utama'],['practice','📝','Latihan'],['progress','📊','Prestasi'],['settings','⚙️','Tetapan']].map(x=>`<button class="navbtn ${active===x[0]?'active':''}" data-view="${x[0]}"><span>${x[1]}</span>${x[2]}</button>`).join('')}</nav>`}
  function shell(content,active=view){app.innerHTML=`<main class="app"><header class="topbar"><div class="brand"><div class="brand-mark">📚</div><div>LatihKu <span class="muted small">KSSR v2</span></div></div><div class="pill">🔥 ${state.streak} · ⭐ ${state.xp} XP</div></header>${content}${nav(active)}</main>`;bindCommon()}
  function bindCommon(){document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{view=b.dataset.view;quiz=null;render()})}
  function installBanner(){if(matchMedia('(display-mode: standalone)').matches)return '';return `<div class="install-banner"><div><strong>📱 Pasang sebagai app</strong><div class="muted small">Add to Home Screen dan guna macam app biasa.</div></div><button class="btn btn-soft" id="installBtn">Pasang</button></div>`}
  function todayStats(){const t=dayKey(),sessions=state.sessions.filter(s=>s.day===t),total=sessions.reduce((a,s)=>a+s.total,0),correct=sessions.reduce((a,s)=>a+s.score,0);return{sessions:sessions.length,total,correct,pct:total?Math.round(correct/total*100):0}}
  function home(){
    const today=todayStats(),recent=state.sessions[0],bank=E.totalStatic().toLocaleString('ms-MY');
    shell(`${installBanner()}<section class="hero"><div class="small" style="font-weight:950;opacity:.92">PRA SEKOLAH · TAHUN 1–6 · TANPA LOGIN</div><h1>Latihan sekolah rendah dalam satu app. 🚀</h1><p>Pilih tahap, subjek dan topik. Mode Belajar beri semakan terus, Mode Ujian semak di akhir. Progress disimpan dalam peranti ini.</p><div class="hero-actions"><button class="btn btn-white" id="heroStart">Mula latihan</button><button class="btn" style="background:rgba(255,255,255,.16);color:white" data-view="progress">Lihat prestasi</button></div></section>
    <section class="section"><div class="card bank-banner"><div class="big">🧠</div><div style="flex:1"><strong>${bank}+ soalan dalam bank</strong><div class="muted small">40 pek modular + Matematik procedural yang boleh jana set baharu berulang kali.</div></div><span class="pill good">v2</span></div></section>
    <section class="section"><div class="section-head"><h2>Hari ini</h2><span class="muted small">Data local sahaja</span></div><div class="grid grid-3"><div class="card stat"><div class="emoji">🎯</div><div><div class="muted small">Ketepatan</div><div class="stat-value">${today.pct}%</div></div></div><div class="card stat"><div class="emoji">✅</div><div><div class="muted small">Soalan</div><div class="stat-value">${today.total}</div></div></div><div class="card stat"><div class="emoji">🔥</div><div><div class="muted small">Streak</div><div class="stat-value">${state.streak} hari</div></div></div></div></section>
    <section class="section"><div class="section-head"><h2>Sambung belajar</h2></div><div class="card click-card" id="continue"><div class="stat"><div class="emoji">${iconSubject(state.prefs.subject)}</div><div style="flex:1"><strong>${esc(levelObj().name)} · ${esc(subObj().name)}</strong><div class="muted small">${esc(state.prefs.topic)} · ${state.prefs.count} soalan · ${state.prefs.mode==='learn'?'Mode Belajar':'Mode Ujian'}</div></div><div>›</div></div></div></section>
    ${recent?`<section class="section"><div class="section-head"><h2>Sesi terakhir</h2></div><div class="card"><div class="history-row"><div><strong>${iconSubject(recent.subject)} ${esc(C.subjects[recent.subject]?.name)}</strong><div class="muted small">${esc(levelObj(recent.level).name)} · ${esc(recent.topic)}</div></div><strong>${recent.pct}%</strong><span class="muted small">${esc(recent.date)}</span></div></div></section>`:''}
    <section class="section"><div class="notice info"><strong>ℹ️ Kandungan latihan sokongan</strong><br><span class="small">LatihKu bukan aplikasi rasmi KPM. Soalan dibina secara original berasaskan kemahiran sekolah rendah dan rujukan kurikulum; bukan salinan bank soalan pihak lain.</span></div></section>`,'home');
    document.querySelector('#heroStart').onclick=()=>{view='practice';render()};document.querySelector('#continue').onclick=()=>{view='practice';render()};bindInstall();
  }
  function practice(){
    const p=state.prefs,subs=E.availableSubjects(p.level);if(!subs.some(s=>s.id===p.subject)){p.subject=subs[0].id;p.topic='Campur Semua'}
    const meta=C.subjects[p.subject],topics=['Campur Semua',...meta.topics];if(!topics.includes(p.topic))p.topic='Campur Semua';save();
    shell(`<section class="section"><div class="section-head"><div><h2>Pilih tahap</h2><div class="muted small">Pra Sekolah hingga Tahun 6.</div></div></div><div class="levels">${C.levels.map(l=>`<div class="card click-card level ${p.level===l.id?'selected':''}" data-level="${l.id}"><div class="emoji">${l.emoji}</div><strong>${l.short}</strong><span class="muted small">${l.name}</span></div>`).join('')}</div></section>
    <section class="section"><div class="section-head"><h2>Subjek</h2></div><div class="grid grid-3">${subs.map(s=>{const info=E.packInfo(p.level,s.id),count=s.id==='math'?'∞ variasi':`${(info?.count||0).toLocaleString('ms-MY')} soalan`;return `<div class="card click-card subject ${p.subject===s.id?'selected':''}" data-subject="${s.id}"><span class="tag">${s.topics.length} topik</span><div class="emoji">${s.emoji}</div><h3>${esc(s.name)}</h3><div class="muted small">Latihan ikut tahap</div><div class="bank-count">${count}</div></div>`}).join('')}</div></section>
    <section class="section"><div class="section-head"><h2>Topik</h2></div><div class="topic-list">${topics.map(t=>`<button class="topic ${p.topic===t?'active':''}" data-topic="${esc(t)}">${esc(t)}</button>`).join('')}</div></section>
    <section class="section"><div class="card setup-box"><div class="setup-row"><strong>Mode</strong><div class="muted small">Belajar semak terus. Ujian simpan jawapan dan semak di akhir.</div><div class="seg"><button data-mode="learn" class="${p.mode==='learn'?'active':''}">💡 Belajar</button><button data-mode="exam" class="${p.mode==='exam'?'active':''}">🧪 Ujian</button></div></div>
    <div class="setup-row"><strong>Tahap kesukaran</strong><div class="seg four">${[['auto','Auto'],['mudah','Mudah'],['sederhana','Sederhana'],['sukar','Sukar']].map(([id,n])=>`<button data-diff="${id}" class="${p.difficulty===id?'active':''}">${n}</button>`).join('')}</div></div>
    <div class="setup-row"><strong>Bilangan soalan</strong><div class="chips">${[5,10,20,30].map(n=>`<button class="chip ${p.count===n?'active':''}" data-count="${n}">${n}</button>`).join('')}</div></div>
    <button class="btn btn-primary btn-wide" id="startQuiz">Mula ${p.count} soalan →</button></div></section>`,'practice');
    document.querySelectorAll('[data-level]').forEach(x=>x.onclick=()=>{p.level=x.dataset.level;p.subject=E.availableSubjects(p.level)[0].id;p.topic='Campur Semua';save();practice()});
    document.querySelectorAll('[data-subject]').forEach(x=>x.onclick=()=>{p.subject=x.dataset.subject;p.topic='Campur Semua';save();practice()});
    document.querySelectorAll('[data-topic]').forEach(x=>x.onclick=()=>{p.topic=x.dataset.topic;save();practice()});
    document.querySelectorAll('[data-mode]').forEach(x=>x.onclick=()=>{p.mode=x.dataset.mode;save();practice()});
    document.querySelectorAll('[data-diff]').forEach(x=>x.onclick=()=>{p.difficulty=x.dataset.diff;save();practice()});
    document.querySelectorAll('[data-count]').forEach(x=>x.onclick=()=>{p.count=+x.dataset.count;save();practice()});
    document.querySelector('#startQuiz').onclick=startQuiz;
  }
  async function startQuiz(){
    updateStreak();const p=state.prefs;showLoading('Sediakan set latihan…',p.subject==='math'?'Menjana soalan Matematik baharu.':'Memuatkan pek soalan yang dipilih.');
    try{const items=await E.makeSet(p.level,p.subject,p.topic,p.count,p.difficulty);quiz={items,i:0,score:0,selected:null,answers:[],started:Date.now(),remaining:p.count*45};view='quiz';hideLoading();renderQuiz();if(state.settings.timer)startTimer()}
    catch(err){hideLoading();toast(err.message||'Gagal memuatkan soalan.');console.error(err)}
  }
  function startTimer(){clearInterval(timerInt);timerInt=setInterval(()=>{if(!quiz)return clearInterval(timerInt);quiz.remaining--;const el=document.querySelector('#timer');if(el){el.textContent=formatTime(quiz.remaining);el.classList.toggle('warn',quiz.remaining<30)}if(quiz.remaining<=0){clearInterval(timerInt);finishQuiz()}},1000)}
  const formatTime=s=>`${Math.floor(Math.max(0,s)/60)}:${String(Math.max(0,s)%60).padStart(2,'0')}`;
  function renderQuiz(){
    const p=state.prefs,item=quiz.items[quiz.i],answered=quiz.selected!==null,progress=Math.round((quiz.i)/quiz.items.length*100),isLearn=p.mode==='learn';
    app.innerHTML=`<main class="app"><header class="topbar"><div class="brand"><button class="btn btn-soft" id="exitQuiz">←</button><div>${iconSubject(p.subject)} ${esc(C.subjects[p.subject].name)}</div></div><div class="pill"><span id="timer" class="timer">${state.settings.timer?formatTime(quiz.remaining):`Soalan ${quiz.i+1}/${quiz.items.length}`}</span></div></header><div class="quiz-wrap"><div class="progress"><i style="width:${progress}%"></i></div><div class="quiz-head"><div class="muted small">${esc(levelObj().name)} · ${isLearn?'Mode Belajar':'Mode Ujian'} · ${p.difficulty==='auto'?'Auto':esc(p.difficulty)}</div><strong>${quiz.score} betul</strong></div><div class="card question-card"><div class="qmeta"><span class="qtag">${esc(item.topic)}</span><span class="qtag">${esc(item.difficulty||'')}</span><span class="qtag">${quiz.i+1} / ${quiz.items.length}</span></div><div class="question">${esc(item.question)}</div><div class="answers">${item.answers.map((a,idx)=>{let cls='';if(answered&&isLearn){if(String(a)===String(item.correct))cls='correct';else if(idx===quiz.selected)cls='wrong';else cls='dim'}return `<button class="answer ${cls}" data-answer="${idx}" ${answered&&isLearn?'disabled':''}><strong>${String.fromCharCode(65+idx)}.</strong> ${esc(a)}</button>`}).join('')}</div>${answered&&isLearn?`<div class="feedback ${String(item.answers[quiz.selected])===String(item.correct)?'good':'bad'}"><strong>${String(item.answers[quiz.selected])===String(item.correct)?'✅ Betul!':'❌ Belum tepat.'}</strong><br>${esc(item.explanation)}</div><div class="quiz-actions"><button class="btn btn-primary" id="nextQ">${quiz.i===quiz.items.length-1?'Lihat keputusan':'Soalan seterusnya →'}</button></div>`:''}</div></div></main>`;
    document.querySelector('#exitQuiz').onclick=()=>{if(confirm('Keluar dari sesi latihan ini? Progress sesi ini tidak disimpan.')){clearInterval(timerInt);quiz=null;view='practice';render()}};
    document.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>answer(+b.dataset.answer));if(answered&&isLearn)document.querySelector('#nextQ').onclick=nextQ;
  }
  function answer(idx){if(quiz.selected!==null&&state.prefs.mode==='learn')return;const item=quiz.items[quiz.i],chosen=item.answers[idx],ok=String(chosen)===String(item.correct);quiz.selected=idx;if(ok)quiz.score++;quiz.answers.push({id:item.id,q:item.question,chosen:String(chosen),correct:String(item.correct),ok,topic:item.topic,subject:state.prefs.subject,explanation:item.explanation});if(state.prefs.mode==='learn'){beep(ok);renderQuiz()}else nextQ()}
  function nextQ(){if(quiz.i>=quiz.items.length-1)return finishQuiz();quiz.i++;quiz.selected=null;renderQuiz()}
  function finishQuiz(){
    clearInterval(timerInt);if(!quiz)return;const p=state.prefs,total=quiz.items.length,score=quiz.score,pct=total?Math.round(score/total*100):0,xp=score*10+(pct===100?50:0);state.xp+=xp;state.answers+=total;state.correct+=score;const now=new Date();state.sessions.unshift({date:now.toLocaleDateString('ms-MY'),day:dayKey(now),ts:Date.now(),level:p.level,subject:p.subject,topic:p.topic,difficulty:p.difficulty,mode:p.mode,score,total,pct,answers:quiz.answers});state.sessions=state.sessions.slice(0,80);save();quiz.result={score,total,pct,xp,answers:quiz.answers};view='result';beep(pct>=60);renderResult();
  }
  function renderResult(){
    const r=quiz.result,msg=r.pct===100?'Perfect! 🔥':r.pct>=80?'Hebat! 🌟':r.pct>=60?'Bagus, teruskan! 💪':'Ulang topik ni lagi 📚';const weak=[...new Set(r.answers.filter(a=>!a.ok).map(a=>a.topic))];
    app.innerHTML=`<main class="app"><header class="topbar"><div class="brand"><div class="brand-mark">🏆</div><div>Keputusan</div></div><div class="pill good">+${r.xp} XP</div></header><div class="quiz-wrap"><div class="card result-hero"><div class="emoji">${r.pct>=80?'🏆':'🎯'}</div><h2>${msg}</h2><div class="result-score">${r.pct}%</div><div class="muted">${r.score} betul daripada ${r.total} soalan</div></div>${weak.length?`<div class="card" style="margin-top:12px"><strong>Topik untuk ulang kaji</strong><div class="topic-list" style="margin-top:10px">${weak.map(w=>`<span class="topic">${esc(w)}</span>`).join('')}</div></div>`:''}<div class="grid grid-2" style="margin-top:12px"><button class="btn btn-primary" id="retry">Cuba set baru</button><button class="btn btn-soft" id="backHome">Balik utama</button></div><div class="card" style="margin-top:12px"><strong>Semakan jawapan</strong>${r.answers.map((a,i)=>`<div class="review-item"><div class="small muted">${i+1}. ${esc(a.topic)}</div><div style="font-weight:850;white-space:pre-line">${esc(a.q)}</div><div class="small" style="margin-top:5px;color:${a.ok?'var(--good)':'var(--bad)'}">${a.ok?'✓':'✗'} Jawapan anda: ${esc(a.chosen)}${a.ok?'':` · Betul: ${esc(a.correct)}`}</div>${!a.ok?`<div class="muted small" style="margin-top:4px">${esc(a.explanation)}</div>`:''}</div>`).join('')}</div></div>${nav('progress')}</main>`;
    bindCommon();document.querySelector('#retry').onclick=startQuiz;document.querySelector('#backHome').onclick=()=>{quiz=null;view='home';render()};
  }
  function progress(){
    const sessions=state.sessions,pct=state.answers?Math.round(state.correct/state.answers*100):0,bySubject={};sessions.forEach(s=>{bySubject[s.subject]??={n:0,c:0,t:0};bySubject[s.subject].n++;bySubject[s.subject].c+=s.score;bySubject[s.subject].t+=s.total});
    const wrongTopics={};sessions.forEach(s=>(s.answers||[]).filter(a=>!a.ok).forEach(a=>{const key=`${s.subject}|${a.topic}`;wrongTopics[key]=(wrongTopics[key]||0)+1}));const weak=Object.entries(wrongTopics).sort((a,b)=>b[1]-a[1]).slice(0,6);
    const badges=[['🌱','Mula Belajar',state.answers>=1],['🔥','Streak 3 Hari',state.streak>=3],['💯','Perfect Score',sessions.some(s=>s.pct===100)],['⭐','500 XP',state.xp>=500],['📚','100 Soalan',state.answers>=100],['🏆','10 Sesi',sessions.length>=10],['🚀','1,000 Soalan',state.answers>=1000],['👑','5,000 XP',state.xp>=5000]];
    shell(`<section class="section"><div class="section-head"><div><h2>Prestasi</h2><div class="muted small">Semua progress disimpan pada peranti ini.</div></div></div><div class="grid grid-3"><div class="card"><div class="muted small">Ketepatan keseluruhan</div><div class="stat-value">${pct}%</div><div class="progress"><i style="width:${pct}%"></i></div></div><div class="card"><div class="muted small">Jumlah soalan</div><div class="stat-value">${state.answers}</div></div><div class="card"><div class="muted small">Jumlah sesi</div><div class="stat-value">${sessions.length}</div></div></div></section>
    <section class="section"><div class="section-head"><h2>Mengikut subjek</h2></div>${Object.keys(bySubject).length?`<div class="grid grid-2">${Object.entries(bySubject).map(([id,v])=>{const p=Math.round(v.c/v.t*100);return `<div class="card"><div class="stat"><div class="emoji">${iconSubject(id)}</div><div style="flex:1"><strong>${esc(C.subjects[id]?.name)}</strong><div class="muted small">${v.n} sesi · ${p}% tepat</div><div class="progress" style="margin-top:8px"><i style="width:${p}%"></i></div></div></div></div>`}).join('')}</div>`:`<div class="card empty">Belum ada rekod. Buat satu latihan dulu 😊</div>`}</section>
    <section class="section"><div class="section-head"><h2>Topik perlu fokus</h2></div><div class="card">${weak.length?weak.map(([key,n])=>{const [sub,topic]=key.split('|');return `<div class="history-row"><div><strong>${iconSubject(sub)} ${esc(topic)}</strong><div class="muted small">${esc(C.subjects[sub]?.name)} · tersalah ${n} kali</div></div><span>🎯</span><span></span></div>`}).join(''):'<div class="empty">Belum cukup data untuk kenal pasti topik lemah.</div>'}</div></section>
    <section class="section"><div class="section-head"><h2>Lencana</h2></div><div class="badgebox">${badges.map(b=>`<div class="badge ${b[2]?'':'locked'}"><div class="emoji">${b[0]}</div><strong>${b[1]}</strong></div>`).join('')}</div></section>
    <section class="section"><div class="section-head"><h2>Sejarah latihan</h2></div><div class="card">${sessions.length?sessions.slice(0,15).map(s=>`<div class="history-row"><div><strong>${iconSubject(s.subject)} ${esc(C.subjects[s.subject]?.name)}</strong><div class="muted small">${esc(levelObj(s.level).short)} · ${esc(s.topic)}</div></div><strong>${s.pct}%</strong><span class="muted small">${esc(s.date)}</span></div>`).join(''):'<div class="empty">Tiada sesi lagi.</div>'}</div></section>`,'progress');
  }
  async function settings(){
    const downloaded=state.settings.offlineDownloadedAt,bytes=formatBytes(E.totalBytes()),bank=E.totalStatic().toLocaleString('ms-MY');
    shell(`<section class="section"><div class="section-head"><div><h2>Tetapan</h2><div class="muted small">Tak perlu akaun atau login.</div></div></div><div class="card"><div class="setting-row"><div><strong>🔊 Bunyi feedback</strong><div class="muted small">Bunyi ringkas bila jawab dalam Mode Belajar.</div></div><button class="toggle ${state.settings.sound?'on':''}" data-toggle="sound"><i></i></button></div><div class="setting-row"><div><strong>⏱️ Timer</strong><div class="muted small">45 saat bagi setiap soalan dalam satu sesi.</div></div><button class="toggle ${state.settings.timer?'on':''}" data-toggle="timer"><i></i></button></div><div class="setting-row"><div><strong>📱 Pasang aplikasi</strong><div class="muted small">Install PWA ke Home Screen.</div></div><button class="btn btn-soft" id="installSettings">Pasang</button></div></div></section>
    <section class="section"><div class="card"><div class="bank-banner"><div class="big">📦</div><div style="flex:1"><strong>Bank soalan offline</strong><div class="muted small">${bank} soalan static · ${bytes} data. Matematik dijana dalam app dan tak perlukan pack tambahan.</div></div></div><div class="notice ${downloaded?'info':''}" style="margin-top:14px">${downloaded?`✅ Semua pek pernah dimuat turun pada ${esc(downloaded)}. Cache browser masih tertakluk kepada pengurusan storage peranti.`:'Untuk pastikan semua subjek boleh dibuka tanpa internet, download semua pek sekali.'}</div><div class="offline-progress hidden" id="offlineProgress"><div class="small"><span id="offlineLabel">0 / 40 pek</span><span id="offlinePct">0%</span></div><div class="progress"><i id="offlineBar" style="width:0%"></i></div></div><div class="grid grid-2" style="margin-top:12px"><button class="btn btn-primary" id="downloadAll">Download semua untuk offline</button><button class="btn btn-soft" id="clearCache">Kosongkan cache soalan</button></div></div></section>
    <section class="section"><div class="card"><h3>Data & privasi</h3><p class="muted small">Keputusan, XP, streak dan sejarah disimpan menggunakan localStorage pada browser/peranti. Tiada akaun pengguna dan app ini tidak memerlukan backend database.</p><button class="btn btn-danger" id="resetData">Padam semua progress</button></div></section>
    <section class="section"><div class="card"><strong>LatihKu KSSR v${esc(C.version)}</strong><div class="muted small">Pra Sekolah · Tahun 1–6 · ${bank}+ bank soalan · PWA modular.</div></div></section>`,'settings');
    document.querySelectorAll('[data-toggle]').forEach(b=>b.onclick=()=>{const k=b.dataset.toggle;state.settings[k]=!state.settings[k];save();settings()});document.querySelector('#installSettings').onclick=installApp;document.querySelector('#resetData').onclick=()=>{if(confirm('Padam semua progress, streak dan sejarah latihan?')){const keepOffline=state.settings.offlineDownloadedAt;state=clone(defaults);state.settings.offlineDownloadedAt=keepOffline;save();toast('Progress dipadam');settings()}};
    document.querySelector('#downloadAll').onclick=downloadAllOffline;document.querySelector('#clearCache').onclick=clearDataCache;
  }
  async function downloadAllOffline(){
    const box=document.querySelector('#offlineProgress'),bar=document.querySelector('#offlineBar'),label=document.querySelector('#offlineLabel'),pct=document.querySelector('#offlinePct'),btn=document.querySelector('#downloadAll');box.classList.remove('hidden');btn.disabled=true;btn.textContent='Downloading…';
    try{await E.downloadAll((done,total)=>{const p=Math.round(done/total*100);bar.style.width=`${p}%`;label.textContent=`${done} / ${total} pek`;pct.textContent=`${p}%`});state.settings.offlineDownloadedAt=new Date().toLocaleString('ms-MY');save();toast('Semua pek soalan selesai dimuat turun ✅');setTimeout(settings,500)}catch(err){toast(`Download tak lengkap: ${err.message}`);btn.disabled=false;btn.textContent='Cuba lagi'}
  }
  async function clearDataCache(){if(!confirm('Kosongkan cache pek soalan? Progress latihan tidak akan dipadam.'))return;E.clearMemory();state.settings.offlineDownloadedAt='';save();if('serviceWorker' in navigator){const reg=await navigator.serviceWorker.ready;reg.active?.postMessage({type:'CLEAR_DATA_CACHE'})}toast('Cache soalan dikosongkan');settings()}
  function installApp(){if(installPrompt){installPrompt.prompt();installPrompt.userChoice.finally(()=>installPrompt=null);return}const ios=/iphone|ipad|ipod/i.test(navigator.userAgent);toast(ios?'Safari: Share → Add to Home Screen':'Browser menu → Install app / Add to Home Screen')}
  function bindInstall(){document.querySelector('#installBtn')?.addEventListener('click',installApp)}
  function render(){clearInterval(timerInt);if(view==='home')home();else if(view==='practice')practice();else if(view==='progress')progress();else if(view==='settings')settings();else if(view==='quiz'&&quiz)renderQuiz();else home();bindInstall()}
  window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e});window.addEventListener('appinstalled',()=>toast('LatihKu berjaya dipasang 🎉'));
  if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('sw.js').catch(console.error));
  render();
})();
