(() => {
  const C=window.LATIH_CONFIG,E=window.LATIH_ENGINE,P=window.LATIH_PRA,L=window.LATIH_LEARNING,A=window.LATIH_ADAPTIVE;
  const app=document.querySelector('#app'),toastEl=document.querySelector('#toast'),loading=document.querySelector('#loading'),loadingTitle=document.querySelector('#loadingTitle'),loadingText=document.querySelector('#loadingText'),restoreFile=document.querySelector('#restoreFile');
  const STORAGE_KEY='latihkuStudyV10';
  const PREV_STORAGE_KEY='latihkuStudyV9';
  const AVATARS=['⚽','🦄','🚀','🦖','🐼','🐱','🌈','⭐','🏎️','👑','🦊','🐸','🧒','👦','👧','🧑‍🚀','👩‍🔬','🧑‍🎨'];
  const defaults={
    schemaVersion:17,meta:{updatedAt:0},profile:{name:'',avatar:'⭐',onboarded:false},
    xp:0,streak:0,lastDay:'',sessions:[],answers:0,correct:0,
    settings:{sound:true,timer:false,offlineDownloadedAt:'',persistentStorage:false},
    prefs:{level:'1',subject:'math',topic:'Campur Semua',mode:'learn',count:10,difficulty:'auto',praActivity:'mix'},
    smartPractice:{seen:{},recentGenerated:{},generatedTotal:0},
    learning:{completed:{},mastery:{},pendingMastery:null,adaptive:{}},
    activeQuiz:null
  };
  let state=load(),view='home',quiz=null,praRun=null,lessonRun=null,onboardStep=state.profile.name?2:1,installPrompt=null,timerInt=null,saveTimer=null;

  function clone(x){return JSON.parse(JSON.stringify(x))}
  function merge(a,b){const o=clone(a);for(const k in (b||{})){o[k]=(b[k]&&typeof b[k]==='object'&&!Array.isArray(b[k]))?merge(o[k]||{},b[k]):b[k]}return o}
  function migrate(s){const m=merge(defaults,s||{});m.schemaVersion=17;if(!m.profile)m.profile=clone(defaults.profile);if(!m.meta)m.meta={updatedAt:0};if(!m.smartPractice)m.smartPractice=clone(defaults.smartPractice);if(!m.learning)m.learning=clone(defaults.learning);if(!m.learning.adaptive)m.learning.adaptive={};if(m.activeQuiz)m.activeQuiz=null;return m}
  function load(){try{const cur=localStorage.getItem(STORAGE_KEY);if(cur)return migrate(JSON.parse(cur));const prev=localStorage.getItem(PREV_STORAGE_KEY);return prev?migrate(JSON.parse(prev)):clone(defaults)}catch{return clone(defaults)}}
  function save(immediate=false){state.meta.updatedAt=Date.now();const run=()=>{try{localStorage.setItem(STORAGE_KEY,JSON.stringify(state))}catch{};idbSave(state).catch(()=>{})};if(immediate){clearTimeout(saveTimer);run()}else{clearTimeout(saveTimer);saveTimer=setTimeout(run,80)}}
  function openDB(){return new Promise((resolve,reject)=>{if(!('indexedDB'in window))return reject(new Error('No IndexedDB'));const r=indexedDB.open('LatihKuStudyDB',1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains('state'))r.result.createObjectStore('state')};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
  async function idbSave(data){const db=await openDB();return new Promise((res,rej)=>{const tx=db.transaction('state','readwrite');tx.objectStore('state').put(clone(data),'main');tx.oncomplete=()=>{db.close();res()};tx.onerror=()=>rej(tx.error)})}
  async function idbLoad(){const db=await openDB();return new Promise((res,rej)=>{const tx=db.transaction('state','readonly'),r=tx.objectStore('state').get('main');r.onsuccess=()=>{db.close();res(r.result||null)};r.onerror=()=>rej(r.error)})}
  async function hydrateMirror(){try{const m=await idbLoad();if(m?.meta?.updatedAt>state.meta.updatedAt){state=migrate(m);localStorage.setItem(STORAGE_KEY,JSON.stringify(state));render()}else{idbSave(state).catch(()=>{})}}catch{}}

  function esc(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
  function toast(m){toastEl.textContent=m;toastEl.classList.add('show');setTimeout(()=>toastEl.classList.remove('show'),2200)}
  function showLoading(title='Memuatkan…',text=''){loadingTitle.textContent=title;loadingText.textContent=text;loading.classList.remove('hidden')}
  function hideLoading(){loading.classList.add('hidden')}
  function dayKey(d=new Date()){return `${d.getFullYear()}-${d.getMonth()+1}-${d.getDate()}`}
  function levelObj(id=state.prefs.level){return C.levels.find(x=>x.id===id)||C.levels[1]}
  function subObj(id=state.prefs.subject){return C.subjects[id]||C.subjects.math}
  function iconSubject(id){return C.subjects[id]?.emoji||'📚'}
  function formatBytes(bytes){if(bytes<1024)return `${bytes} B`;if(bytes<1024**2)return `${(bytes/1024).toFixed(1)} KB`;return `${(bytes/1024**2).toFixed(1)} MB`}
  function formatTime(s){const m=Math.floor(Math.max(0,s)/60),r=Math.max(0,s)%60;return `${m}:${String(r).padStart(2,'0')}`}
  function beep(ok=true){if(!state.settings.sound)return;try{const A=window.AudioContext||window.webkitAudioContext,ctx=new A(),osc=ctx.createOscillator(),gain=ctx.createGain();osc.type='sine';osc.frequency.value=ok?690:230;gain.gain.value=.025;osc.connect(gain);gain.connect(ctx.destination);osc.start();osc.stop(ctx.currentTime+.08);osc.onended=()=>ctx.close()}catch{}}
  function todayStats(){const t=dayKey(),ss=state.sessions.filter(s=>s.day===t),total=ss.reduce((a,s)=>a+s.total,0),correct=ss.reduce((a,s)=>a+s.score,0);return{sessions:ss.length,total,correct,pct:total?Math.round(correct/total*100):0}}
  function updateStreak(){const t=dayKey();if(state.lastDay!==t){const y=new Date();y.setDate(y.getDate()-1);state.streak=state.lastDay===dayKey(y)?state.streak+1:1;state.lastDay=t}save(true)}
  function activeQuizResume(){return state.activeQuiz?.items?.length&&state.activeQuiz.i<state.activeQuiz.items.length}
  function smartPackKey(p=state.prefs){return `${p.level}:${p.subject}`}
  function smartContext(p=state.prefs){
    const key=smartPackKey(p),weakTopics={};
    state.sessions.filter(s=>s.level===p.level&&s.subject===p.subject).forEach(s=>(s.answers||[]).forEach(a=>{if(!a.ok)weakTopics[a.topic]=(weakTopics[a.topic]||0)+1}));
    return {seenIds:state.smartPractice.seen[key]||[],recentGenerated:state.smartPractice.recentGenerated[key]||[],weakTopics};
  }
  function recordSmartProgress(p,answers=[]){
    const key=smartPackKey(p),seen=new Set(state.smartPractice.seen[key]||[]),recent=[...(state.smartPractice.recentGenerated[key]||[])];let generated=0;
    for(const a of answers){if(a.smartSignature){recent.push(a.smartSignature);generated++;}else if(a.id&&!String(a.id).startsWith('MATH-')&&!String(a.id).startsWith('SMART-'))seen.add(String(a.id));}
    state.smartPractice.seen[key]=[...seen];state.smartPractice.recentGenerated[key]=recent.slice(-300);state.smartPractice.generatedTotal=(state.smartPractice.generatedTotal||0)+generated;
  }

  function onboard(){
    if(onboardStep===1){
      app.innerHTML=`<main class="welcome-page"><section class="welcome-card"><div class="welcome-visual"><div class="logo-bubble">📚</div><div class="spark s1">✦</div><div class="spark s2">✦</div><div class="spark s3">★</div><h1>LatihKu</h1><p>Belajar ikut tahap, subjek dan topik — ringkas, kemas dan terus mula.</p><div class="mini-books"><span>🔢</span><span>📖</span><span>🔬</span><span>🔤</span></div></div><div class="welcome-form"><span class="eyebrow">LANGKAH 1 DARIPADA 2</span><h2>Siapa nama anda?</h2><p>Nama disimpan dulu supaya tak hilang bila pilih sticker.</p><input id="firstName" class="name-input" maxlength="20" autocomplete="off" placeholder="Contoh: Aiman" value="${esc(state.profile.name)}"><button class="primary-cta" id="nextSticker">Seterusnya <span>→</span></button><small class="privacy-line">🔒 Tiada akaun · Tiada iklan · Progress local</small></div></section></main>`;
      const input=document.querySelector('#firstName');input.focus();
      const next=()=>{const n=input.value.trim();if(!n){input.classList.add('shake');setTimeout(()=>input.classList.remove('shake'),450);return}state.profile.name=n;save(true);onboardStep=2;onboard()};
      document.querySelector('#nextSticker').onclick=next;input.addEventListener('keydown',e=>{if(e.key==='Enter')next()});return;
    }
    app.innerHTML=`<main class="welcome-page"><section class="welcome-card"><div class="welcome-visual sticker-preview"><div class="big-sticker">${state.profile.avatar}</div><h1>${esc(state.profile.name)}</h1><p>Pilih sticker yang paling kamu suka. Boleh tukar lagi dalam Tetapan.</p></div><div class="welcome-form"><span class="eyebrow">LANGKAH 2 DARIPADA 2</span><h2>Pilih sticker profil</h2><p>Bola, unicorn, dinosaur, roket dan banyak lagi.</p><div class="avatar-picker sticker-grid">${AVATARS.map(a=>`<button class="avatar-choice ${state.profile.avatar===a?'active':''}" data-avatar="${a}">${a}</button>`).join('')}</div><div class="onboard-actions"><button class="soft-btn large" id="backName">← Tukar nama</button><button class="primary-cta" id="beginBtn">Mula Belajar <span>→</span></button></div><small class="privacy-line">Nama: <b>${esc(state.profile.name)}</b></small></div></section></main>`;
    document.querySelectorAll('[data-avatar]').forEach(b=>b.onclick=()=>{state.profile.avatar=b.dataset.avatar;save(true);onboard()});
    document.querySelector('#backName').onclick=()=>{onboardStep=1;onboard()};
    document.querySelector('#beginBtn').onclick=()=>{state.profile.onboarded=true;save(true);view='home';render()};
  }


  function nav(active){return `<nav class="bottomnav five">${[['home','⌂','Utama'],['learnHub','📚','Belajar'],['practice','✎','Latihan'],['progress','▥','Prestasi'],['settings','⚙','Tetapan']].map(([id,ic,n])=>`<button class="navbtn ${active===id?'active':''}" data-view="${id}"><span>${ic}</span><b>${n}</b></button>`).join('')}</nav>`}
  function topbar(){return `<header class="topbar"><button class="student-chip" data-view="settings"><span class="student-avatar">${state.profile.avatar}</span><span><small>Hai,</small><b>${esc(state.profile.name)}</b></span></button><div class="top-stats"><span>🔥 <b>${state.streak}</b></span><span>⭐ <b>${state.xp}</b></span></div></header>`}
  function shell(content,active=view){app.innerHTML=`<main class="app">${topbar()}<div class="page">${content}</div>${nav(active)}</main>`;bindCommon()}
  function bindCommon(){document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{view=b.dataset.view;quiz=null;render()})}
  function installBanner(){if(matchMedia('(display-mode: standalone)').matches)return '';return `<div class="install-banner"><div><b>📱 Pasang LatihKu</b><small>Guna macam app biasa dan lebih mudah buka setiap hari.</small></div><button class="soft-btn" id="installBtn">Pasang</button></div>`}


  function subjectDesc(id){return ({math:'Nombor, operasi, wang, masa & bentuk',bm:'Kefahaman, tatabahasa, kosa kata & ejaan',en:'Vocabulary, grammar & comprehension',sci:'Manusia, haiwan, tumbuhan, bahan & tenaga',hist:'Sejarah Malaysia, tokoh & zaman',islam:'Akidah, ibadah, sirah, akhlak & Jawi',moral:'Nilai, tanggungjawab & hubungan sosial',pjpk:'Kecergasan, kesihatan & keselamatan',pra:'Aktiviti awal sebelum Tahun 1'})[id]||'Latihan mengikut topik';}
  function setLevel(id){state.prefs.level=id;const subs=E.availableSubjects(id);state.prefs.subject=subs[0]?.id||'math';state.prefs.topic='Campur Semua';if(+id<4&&state.prefs.mode==='uasa')state.prefs.mode='exam';if(id==='pra')state.prefs.praActivity=state.prefs.praActivity||'mix';save(true);}
  function praTiles(){return `<div class="pra-activity-grid">${P.activities.map(a=>`<button class="pra-activity ${a.accent}" data-pra="${a.id}"><span>${a.icon}</span><div><b>${esc(a.name)}</b><small>${esc(a.desc)}</small></div><em>›</em></button>`).join('')}</div>`}
  function home(){
    const today=todayStats(),recent=state.sessions[0],bank=E.totalStatic().toLocaleString('ms-MY'),subs=E.availableSubjects(state.prefs.level),isPra=state.prefs.level==='pra';
    const categories=isPra?praTiles():`<div class="quick-subject-grid rich">${subs.map(s=>`<button class="quick-subject rich-card" data-learn-subject="${s.id}"><span class="subject-icon subject-${s.id}">${s.emoji}</span><div><b>${esc(s.name)}</b><small>${esc(subjectDesc(s.id))}</small></div><strong>›</strong></button>`).join('')}</div>`;
    shell(`${installBanner()}<section class="home-hero"><div class="hero-copy"><span class="eyebrow light">${esc(levelObj().name).toUpperCase()}</span><h1>Jom belajar, ${esc(state.profile.name)}! 👋</h1><p>${isPra?'Pilih aktiviti ceria — bukan peperiksaan formal. Ada huruf, nombor, lukis, mewarna, memory dan banyak lagi.':'Belajar konsep dulu, cuba bersama, buat aktiviti interaktif dan akhirnya uji penguasaan.'}</p><div class="hero-buttons"><button class="hero-primary" id="heroStart">${isPra?'Mula Belajar':'Mula Belajar'}</button>${!isPra?'<button class="hero-secondary" id="quickPractice">Latihan Pantas</button>':''}${activeQuizResume()?'<button class="hero-secondary" id="resumeQuiz">Sambung Sesi</button>':''}</div></div><div class="hero-art"><div class="book-stack"><span>${isPra?'🎨':'📘'}</span><span>${isPra?'🔤':'📗'}</span><span>${isPra?'🧠':'📙'}</span></div><div class="hero-star">★</div></div></section>
    <section class="content-section"><div class="section-title"><div><small>TAHAP</small><h2>Pilih tahap</h2></div></div><div class="home-level-row">${C.levels.map(l=>`<button class="home-level ${state.prefs.level===l.id?'active':''}" data-home-level="${l.id}"><span>${l.emoji}</span><b>${l.short}</b><small>${l.name}</small></button>`).join('')}</div></section>
    <section class="stats-row"><div class="metric-card"><span>🎯</span><div><small>Ketepatan hari ini</small><b>${today.pct}%</b></div></div><div class="metric-card"><span>✅</span><div><small>Aktiviti/soalan hari ini</small><b>${today.total}</b></div></div><div class="metric-card"><span>🔥</span><div><small>Streak</small><b>${state.streak} hari</b></div></div></section>
    <section class="content-section"><div class="section-title"><div><small>${isPra?'AKTIVITI PRA':'SUBJEK'}</small><h2>${isPra?'Pilih corak aktiviti':'Pilih kategori belajar'}</h2></div><span>${isPra?'12 aktiviti':`${bank}+ soalan`}</span></div>${categories}</section>
    ${!isPra?`<section class="content-section"><div class="simple-note kpm-note"><b>📘 Rujukan pentaksiran</b><span>Latihan original. Untuk Tahun 4–6, Mode Ujian + Auto menggunakan agihan aras 5:3:2 sebagai rujukan format UASA KPM; ia bukan kertas rasmi KPM.</span></div></section>`:`<section class="content-section"><div class="simple-note kpm-note"><b>🧒 Pra Sekolah</b><span>Fokus pada aktiviti dan hasil kerja — bukan peperiksaan formal. Mewarna, lukis, memory dan pendengaran boleh dibuat terus dalam app.</span></div></section>`}
    ${recent?`<section class="content-section"><div class="section-title"><div><small>TERKINI</small><h2>Sesi terakhir</h2></div></div><div class="recent-card"><span class="subject-icon subject-${recent.subject}">${iconSubject(recent.subject)}</span><div><b>${esc(C.subjects[recent.subject]?.name||'Aktiviti')}</b><small>${esc(levelObj(recent.level).name)} · ${esc(recent.topic)}</small></div><strong>${recent.pct}%</strong></div></section>`:''}`,'home');
    document.querySelector('#heroStart').onclick=()=>{view='learnHub';render()};
    document.querySelector('#quickPractice')?.addEventListener('click',()=>{view='practice';render()});
    document.querySelector('#resumeQuiz')?.addEventListener('click',resumeSavedQuiz);
    document.querySelectorAll('[data-home-level]').forEach(b=>b.onclick=()=>{setLevel(b.dataset.homeLevel);home()});
    document.querySelectorAll('[data-learn-subject]').forEach(b=>b.onclick=()=>{state.prefs.subject=b.dataset.learnSubject;state.prefs.topic=C.subjects[state.prefs.subject]?.topics?.[0]||'Campur Semua';save(true);view='learnHub';render()});
    document.querySelectorAll('[data-pra]').forEach(b=>b.onclick=()=>startPraActivity(b.dataset.pra));
    bindInstall();
  }

  function uasaEligible(level,subject){return +level>=4&&['bm','en','math','sci','hist'].includes(subject)}
  function modeLabel(mode){return mode==='learn'?'Mode Belajar':mode==='uasa'?'Latihan Format UASA':'Mode Ujian'}
  function practice(){
    const p=state.prefs,subs=E.availableSubjects(p.level);if(!subs.some(s=>s.id===p.subject)){p.subject=subs[0].id;p.topic='Campur Semua'}
    if(p.level==='pra'){
      shell(`<section class="practice-header"><span class="eyebrow">PRA SEKOLAH</span><h1>Main sambil belajar</h1><p>Pilih satu aktiviti. Untuk Pra, kita utamakan interaksi, pemerhatian dan hasil kerja — bukan peperiksaan formal.</p></section>
      <section class="chooser-block"><div class="step-title"><span>1</span><div><b>Pilih tahap</b><small>Boleh tukar ke Tahun 1–6 bila-bila masa</small></div></div><div class="level-row">${C.levels.map(l=>`<button class="level-card ${p.level===l.id?'active':''}" data-level="${l.id}"><span>${l.emoji}</span><b>${l.short}</b><small>${l.name}</small></button>`).join('')}</div></section>
      <section class="chooser-block"><div class="step-title"><span>2</span><div><b>Pilih corak aktiviti</b><small>Macam menu aktiviti kanak-kanak — tekan dan terus mula</small></div></div>${praTiles()}</section>`,'practice');
      document.querySelectorAll('[data-level]').forEach(x=>x.onclick=()=>{setLevel(x.dataset.level);practice()});
      document.querySelectorAll('[data-pra]').forEach(b=>b.onclick=()=>startPraActivity(b.dataset.pra));return;
    }
    const meta=C.subjects[p.subject],topics=['Campur Semua',...meta.topics];if(!topics.includes(p.topic))p.topic='Campur Semua';if(p.mode==='uasa'&&!uasaEligible(p.level,p.subject))p.mode='exam';save();
    const eligibleUasa=uasaEligible(p.level,p.subject),uasaAuto=p.mode==='uasa';
    shell(`<section class="practice-header"><span class="eyebrow">SEDIAKAN LATIHAN</span><h1>Pilih apa yang nak belajar</h1><p>Kategori visual, topik jelas dan terus mula.</p></section>
    <section class="chooser-block"><div class="step-title"><span>1</span><div><b>Pilih tahap</b><small>Pra Sekolah hingga Tahun 6</small></div></div><div class="level-row">${C.levels.map(l=>`<button class="level-card ${p.level===l.id?'active':''}" data-level="${l.id}"><span>${l.emoji}</span><b>${l.short}</b><small>${l.name}</small></button>`).join('')}</div></section>
    <section class="chooser-block"><div class="step-title"><span>2</span><div><b>Pilih kategori</b><small>Warna berbeza untuk mudahkan budak cam subjek</small></div></div><div class="category-subject-grid">${subs.map(s=>{const info=E.packInfo(p.level,s.id),count=s.id==='math'?'Variasi dinamik':`${(info?.count||0).toLocaleString('ms-MY')} curated + Smart`;return `<button class="category-subject subject-bg-${s.id} ${p.subject===s.id?'active':''}" data-subject="${s.id}"><span class="subject-icon subject-${s.id}">${s.emoji}</span><div><b>${esc(s.name)}</b><small>${esc(subjectDesc(s.id))}</small><em>${count}</em></div><strong>✓</strong></button>`}).join('')}</div></section>
    <section class="chooser-block"><div class="step-title"><span>3</span><div><b>Pilih corak soalan / topik</b><small>Boleh campur semua topik</small></div></div><div class="topic-pattern-grid">${topics.map((t,i)=>`<button class="topic-pattern p${i%6} ${p.topic===t?'active':''}" data-topic="${esc(t)}"><span>${t==='Campur Semua'?'🎲':iconSubject(p.subject)}</span><b>${esc(t)}</b></button>`).join('')}</div></section>
    <section class="chooser-block"><div class="step-title"><span>4</span><div><b>Tetapan latihan</b><small>Pilih mode, kesukaran dan bilangan soalan</small></div></div><div class="mode-grid ${eligibleUasa?'three':''}"><button class="mode-card learn ${p.mode==='learn'?'active':''}" data-mode="learn"><span>📘</span><div><b>Mode Belajar</b><small>Jawab dahulu, kemudian lihat penerangan</small></div></button><button class="mode-card exam ${p.mode==='exam'?'active':''}" data-mode="exam"><span>📝</span><div><b>Mode Ujian</b><small>Semak semua jawapan di akhir</small></div></button>${eligibleUasa?`<button class="mode-card uasa ${p.mode==='uasa'?'active':''}" data-mode="uasa"><span>🏫</span><div><b>Format UASA</b><small>KPM-aligned · aras 5:3:2 · jenis item ikut subjek</small></div></button>`:''}</div>${eligibleUasa?`<div class="kpm-note"><b>🏫 KPM-aligned</b><span>Mode ini ikut struktur/jenis item rasmi setakat yang sesuai untuk auto-marking. Ia bukan salinan kertas peperiksaan sekolah.</span></div>`:''}<div class="setup-split"><div><label>Kesukaran ${uasaAuto?'<span class="uasa-pill">5:3:2</span>':''}</label><div class="segmented">${[['auto',p.mode==='uasa'?'Auto · 5:3:2':'Auto'],['mudah','Mudah'],['sederhana','Sederhana'],['sukar','Sukar']].map(([id,n])=>`<button data-diff="${id}" class="${p.difficulty===id?'active':''}" ${p.mode==='uasa'&&id!=='auto'?'disabled':''}>${n}</button>`).join('')}</div></div><div><label>Bilangan soalan</label><div class="count-row">${[5,10,20,30].map(n=>`<button data-count="${n}" class="${p.count===n?'active':''}">${n}</button>`).join('')}</div></div></div><button class="start-btn" id="startQuiz">Mula ${p.count} Soalan <span>→</span></button></section>`,'practice');
    document.querySelectorAll('[data-level]').forEach(x=>x.onclick=()=>{setLevel(x.dataset.level);practice()});
    document.querySelectorAll('[data-subject]').forEach(x=>x.onclick=()=>{p.subject=x.dataset.subject;p.topic='Campur Semua';if(p.mode==='uasa'&&!uasaEligible(p.level,p.subject))p.mode='exam';save(true);practice()});
    document.querySelectorAll('[data-topic]').forEach(x=>x.onclick=()=>{p.topic=x.dataset.topic;save(true);practice()});
    document.querySelectorAll('[data-mode]').forEach(x=>x.onclick=()=>{p.mode=x.dataset.mode;if(p.mode==='uasa')p.difficulty='auto';save(true);practice()});
    document.querySelectorAll('[data-diff]').forEach(x=>x.onclick=()=>{p.difficulty=x.dataset.diff;save(true);practice()});
    document.querySelectorAll('[data-count]').forEach(x=>x.onclick=()=>{p.count=+x.dataset.count;save(true);practice()});
    document.querySelector('#startQuiz').onclick=startQuiz;
  }

  function startPraActivity(id){
    const a=P.byId(id);state.prefs.level='pra';state.prefs.subject='pra';state.prefs.praActivity=id;save(true);
    if(a.kind==='quiz'){state.prefs.topic=a.topic||'Campur Semua';state.prefs.mode='learn';state.prefs.difficulty='mudah';state.prefs.count=id==='mix'?10:5;save(true);startQuiz();return}
    praRun={id,activity:a};view='praSpecial';renderPraSpecial();
  }
  function praExit(){praRun=null;view='practice';render()}
  function recordPraActivity(topic,score,total,extra={}){
    updateStreak();const xp=Math.max(5,score*5),pct=total?Math.round(score/total*100):100;state.xp+=xp;state.answers+=total;state.correct+=score;const now=new Date();state.sessions.unshift({date:now.toLocaleDateString('ms-MY'),day:dayKey(now),ts:Date.now(),level:'pra',subject:'pra',topic,difficulty:'mudah',mode:'activity',score,total,pct,answers:[],...extra});state.sessions=state.sessions.slice(0,100);const pending=state.learning.pendingMastery;if(pending?.subject==='pra'){state.learning.mastery[pending.key]=Math.max(state.learning.mastery[pending.key]||0,pct);if(pct>=80)state.learning.completed[pending.key]=Date.now();state.learning.pendingMastery=null;}save(true);return {xp};
  }
  function praDone(title,emoji='🌟',score=1,total=1,extra={}){
    const reward=recordPraActivity(title,score,total,extra);praRun={done:true,title,emoji,xp:reward.xp,score,total};renderPraSpecial();beep(true)
  }
  function renderPraSpecial(){
    if(!praRun)return praExit();
    if(praRun.done){shell(`<section class="pra-done"><div>${praRun.emoji}</div><small>AKTIVITI SELESAI</small><h1>Bagus, ${esc(state.profile.name)}!</h1><p>${esc(praRun.title)} selesai · +${praRun.xp} XP</p><div class="result-actions"><button class="start-btn" id="praAgain">Main Lagi</button><button class="soft-btn large" id="praBack">Pilih Aktiviti</button></div></section>`,'practice');document.querySelector('#praAgain').onclick=()=>startPraActivity(state.prefs.praActivity);document.querySelector('#praBack').onclick=praExit;return}
    const kind=praRun.activity.kind;if(kind==='draw')return renderPraDraw();if(kind==='color')return renderPraColor();if(kind==='memory')return renderPraMemory();if(kind==='listen')return renderPraListen();if(kind==='order')return renderPraOrder();praExit();
  }
  function praShell(title,subtitle,body){shell(`<section class="pra-special-head"><button class="icon-btn" id="praExit">←</button><div><small>PRA SEKOLAH</small><h1>${title}</h1><p>${subtitle}</p></div></section>${body}`,'practice');document.querySelector('#praExit').onclick=praExit}
  const PRA_DRAW_SAMPLES=[
    {id:'blank',name:'Canvas kosong',icon:'＋',type:'blank'},
    {id:'A',name:'Huruf A',icon:'A',type:'text',value:'A'},
    {id:'B',name:'Huruf B',icon:'B',type:'text',value:'B'},
    {id:'1',name:'Nombor 1',icon:'1',type:'text',value:'1'},
    {id:'circle',name:'Bulatan',icon:'○',type:'text',value:'○'},
    {id:'triangle',name:'Segi tiga',icon:'△',type:'text',value:'△'},
    {id:'square',name:'Segi empat',icon:'□',type:'text',value:'□'},
    {id:'star',name:'Bintang',icon:'☆',type:'text',value:'☆'},
    {id:'heart',name:'Hati',icon:'♡',type:'text',value:'♡'},
    {id:'house',name:'Rumah',icon:'⌂',type:'svg',value:'<svg viewBox="0 0 760 430" aria-hidden="true"><path d="M220 220 L380 90 L540 220"/><rect x="255" y="215" width="250" height="155" rx="8"/><rect x="355" y="285" width="60" height="85" rx="5"/><rect x="285" y="255" width="55" height="50" rx="5"/><rect x="425" y="255" width="55" height="50" rx="5"/></svg>'}
  ];
  const PRA_COLOR_SAMPLES=[
    {id:'fruit',name:'Buah',icon:'🍎',label:'Epal',svg:'<svg viewBox="0 0 700 420" aria-label="Line art buah epal"><rect width="700" height="420" fill="#fbfeff"/><path class="paint-region" data-default="#ffffff" d="M352 130 C295 88 205 130 205 224 C205 318 277 360 350 360 C423 360 495 318 495 224 C495 130 405 88 352 130Z" fill="#ffffff" stroke="#344f69" stroke-width="8"/><path class="paint-region" data-default="#ffffff" d="M354 128 C370 75 414 66 447 86 C421 116 389 129 354 128Z" fill="#ffffff" stroke="#344f69" stroke-width="8"/><path d="M354 130 C350 102 356 82 370 60" fill="none" stroke="#344f69" stroke-width="9" stroke-linecap="round"/></svg>'},
    {id:'animal',name:'Haiwan',icon:'🐟',label:'Ikan',svg:'<svg viewBox="0 0 700 420" aria-label="Line art ikan"><rect width="700" height="420" fill="#fbfeff"/><ellipse class="paint-region" data-default="#ffffff" cx="335" cy="215" rx="175" ry="105" fill="#ffffff" stroke="#344f69" stroke-width="8"/><polygon class="paint-region" data-default="#ffffff" points="500,215 625,125 615,300" fill="#ffffff" stroke="#344f69" stroke-width="8"/><path class="paint-region" data-default="#ffffff" d="M310 120 Q365 55 420 130 Q365 147 310 120Z" fill="#ffffff" stroke="#344f69" stroke-width="8"/><path class="paint-region" data-default="#ffffff" d="M310 310 Q365 365 420 300 Q365 280 310 310Z" fill="#ffffff" stroke="#344f69" stroke-width="8"/><circle cx="235" cy="190" r="12" fill="#344f69"/><path d="M230 245 Q270 270 310 245" fill="none" stroke="#344f69" stroke-width="7" stroke-linecap="round"/></svg>'},
    {id:'house',name:'Rumah',icon:'🏠',label:'Rumah',svg:'<svg viewBox="0 0 700 420" aria-label="Line art rumah"><rect width="700" height="420" fill="#fbfeff"/><polygon class="paint-region" data-default="#ffffff" points="165,205 350,70 535,205" fill="#ffffff" stroke="#344f69" stroke-width="8"/><rect class="paint-region" data-default="#ffffff" x="205" y="200" width="290" height="165" rx="8" fill="#ffffff" stroke="#344f69" stroke-width="8"/><rect class="paint-region" data-default="#ffffff" x="325" y="280" width="62" height="85" rx="6" fill="#ffffff" stroke="#344f69" stroke-width="7"/><rect class="paint-region" data-default="#ffffff" x="245" y="240" width="58" height="55" rx="6" fill="#ffffff" stroke="#344f69" stroke-width="7"/><rect class="paint-region" data-default="#ffffff" x="410" y="240" width="58" height="55" rx="6" fill="#ffffff" stroke="#344f69" stroke-width="7"/></svg>'},
    {id:'flower',name:'Bunga',icon:'🌼',label:'Bunga',svg:'<svg viewBox="0 0 700 420" aria-label="Line art bunga"><rect width="700" height="420" fill="#fbfeff"/><path d="M350 230 L350 365" stroke="#344f69" stroke-width="10" stroke-linecap="round"/><ellipse class="paint-region" data-default="#ffffff" cx="280" cy="330" rx="65" ry="28" transform="rotate(25 280 330)" fill="#ffffff" stroke="#344f69" stroke-width="8"/><ellipse class="paint-region" data-default="#ffffff" cx="420" cy="330" rx="65" ry="28" transform="rotate(-25 420 330)" fill="#ffffff" stroke="#344f69" stroke-width="8"/><circle class="paint-region" data-default="#ffffff" cx="350" cy="185" r="52" fill="#ffffff" stroke="#344f69" stroke-width="8"/><ellipse class="paint-region" data-default="#ffffff" cx="350" cy="92" rx="45" ry="65" fill="#ffffff" stroke="#344f69" stroke-width="8"/><ellipse class="paint-region" data-default="#ffffff" cx="443" cy="185" rx="65" ry="45" fill="#ffffff" stroke="#344f69" stroke-width="8"/><ellipse class="paint-region" data-default="#ffffff" cx="350" cy="278" rx="45" ry="65" fill="#ffffff" stroke="#344f69" stroke-width="8"/><ellipse class="paint-region" data-default="#ffffff" cx="257" cy="185" rx="65" ry="45" fill="#ffffff" stroke="#344f69" stroke-width="8"/></svg>'},
    {id:'vehicle',name:'Kenderaan',icon:'🚗',label:'Kereta',svg:'<svg viewBox="0 0 700 420" aria-label="Line art kereta"><rect width="700" height="420" fill="#fbfeff"/><path class="paint-region" data-default="#ffffff" d="M130 255 L175 175 Q190 145 225 145 H430 Q460 145 480 175 L530 255 H575 Q600 255 600 285 V325 H100 V285 Q100 255 130 255Z" fill="#ffffff" stroke="#344f69" stroke-width="8"/><path class="paint-region" data-default="#ffffff" d="M220 165 H315 V235 H180Z" fill="#ffffff" stroke="#344f69" stroke-width="7"/><path class="paint-region" data-default="#ffffff" d="M335 165 H425 Q445 165 460 190 L488 235 H335Z" fill="#ffffff" stroke="#344f69" stroke-width="7"/><circle class="paint-region" data-default="#ffffff" cx="205" cy="325" r="48" fill="#ffffff" stroke="#344f69" stroke-width="9"/><circle class="paint-region" data-default="#ffffff" cx="495" cy="325" r="48" fill="#ffffff" stroke="#344f69" stroke-width="9"/><circle cx="205" cy="325" r="17" fill="#344f69"/><circle cx="495" cy="325" r="17" fill="#344f69"/></svg>'},
    {id:'shapes',name:'Bentuk',icon:'🔷',label:'Bentuk',svg:'<svg viewBox="0 0 700 420" aria-label="Line art bentuk asas"><rect width="700" height="420" fill="#fbfeff"/><circle class="paint-region" data-default="#ffffff" cx="155" cy="145" r="75" fill="#ffffff" stroke="#344f69" stroke-width="8"/><polygon class="paint-region" data-default="#ffffff" points="350,60 260,215 440,215" fill="#ffffff" stroke="#344f69" stroke-width="8"/><rect class="paint-region" data-default="#ffffff" x="505" y="75" width="130" height="130" rx="8" fill="#ffffff" stroke="#344f69" stroke-width="8"/><polygon class="paint-region" data-default="#ffffff" points="155,260 180,315 240,320 195,360 210,415 155,382 100,415 115,360 70,320 130,315" fill="#ffffff" stroke="#344f69" stroke-width="8"/><rect class="paint-region" data-default="#ffffff" x="300" y="275" width="250" height="100" rx="12" fill="#ffffff" stroke="#344f69" stroke-width="8"/></svg>'}
  ];
  function drawGuideMarkup(sample){
    if(!sample||sample.type==='blank')return '<div class="trace-target draw-guide blank-guide"><span>Canvas kosong</span></div>';
    if(sample.type==='svg')return `<div class="trace-target draw-guide svg-guide">${sample.value}</div>`;
    return `<div class="trace-target draw-guide">${esc(sample.value)}</div>`;
  }
  function renderPraDraw(){
    praRun.drawSample=praRun.drawSample||'blank';praRun.drawColor=praRun.drawColor||'#173f73';praRun.drawSize=praRun.drawSize||14;praRun.drawEraser=!!praRun.drawEraser;praRun.drawStrokes=praRun.drawStrokes||[];
    const sample=PRA_DRAW_SAMPLES.find(x=>x.id===praRun.drawSample)||PRA_DRAW_SAMPLES[0];
    praShell('✍️ Melukis','Pilih sample untuk ditiru atau guna canvas kosong. Ada brush, warna, saiz, eraser, undo dan clear.',`<section class="draw-card"><div class="sample-strip"><div><b>Pilih sample / mode</b><small>Boleh tukar antara contoh dan canvas kosong</small></div><div class="draw-sample-grid">${PRA_DRAW_SAMPLES.map(x=>`<button data-draw-sample="${x.id}" class="${x.id===sample.id?'active':''}"><span>${x.icon}</span><small>${x.name}</small></button>`).join('')}</div></div><div class="trace-wrap">${drawGuideMarkup(sample)}<canvas id="drawCanvas" width="760" height="430"></canvas></div><div class="draw-tools v12"><div class="tool-group"><label>Warna</label><div class="draw-colors">${['#173f73','#e84545','#ff9d22','#2fae68','#3d8df5','#7957d5','#111111'].map(c=>`<button style="--c:${c}" data-draw-color="${c}" class="${!praRun.drawEraser&&praRun.drawColor===c?'active':''}" aria-label="Warna"></button>`).join('')}</div></div><div class="tool-group"><label>Saiz brush</label><div class="brush-sizes">${[[7,'S'],[14,'M'],[24,'L'],[36,'XL']].map(([n,l])=>`<button data-brush-size="${n}" class="${praRun.drawSize===n?'active':''}"><i style="--s:${Math.max(6,n/2)}px"></i>${l}</button>`).join('')}</div></div><div class="draw-action-row"><button class="soft-btn ${praRun.drawEraser?'tool-active':''}" id="eraserDraw">🧽 Eraser</button><button class="soft-btn" id="undoDraw" ${praRun.drawStrokes.length?'':'disabled'}>↶ Undo</button><button class="soft-btn" id="clearDraw">Clear</button><button class="start-btn small-start" id="doneDraw">Siap ✓</button></div></div></section>`);
    const c=document.querySelector('#drawCanvas'),ctx=c.getContext('2d');ctx.lineCap='round';ctx.lineJoin='round';let drawing=false,current=null;
    function pt(e){const r=c.getBoundingClientRect();return[(e.clientX-r.left)*c.width/r.width,(e.clientY-r.top)*c.height/r.height]}
    function paintStroke(st){if(!st||!st.points.length)return;ctx.save();ctx.globalCompositeOperation=st.eraser?'destination-out':'source-over';ctx.strokeStyle=st.color;ctx.fillStyle=st.color;ctx.lineWidth=st.size;ctx.lineCap='round';ctx.lineJoin='round';const pts=st.points;if(pts.length===1){ctx.beginPath();ctx.arc(pts[0][0],pts[0][1],st.size/2,0,Math.PI*2);ctx.fill()}else{ctx.beginPath();ctx.moveTo(pts[0][0],pts[0][1]);for(let i=1;i<pts.length;i++)ctx.lineTo(pts[i][0],pts[i][1]);ctx.stroke()}ctx.restore()}
    function redraw(){ctx.clearRect(0,0,c.width,c.height);praRun.drawStrokes.forEach(paintStroke)}
    redraw();
    c.onpointerdown=e=>{drawing=true;c.setPointerCapture(e.pointerId);current={color:praRun.drawColor,size:praRun.drawSize,eraser:praRun.drawEraser,points:[pt(e)]};praRun.drawStrokes.push(current);paintStroke(current)};
    c.onpointermove=e=>{if(!drawing||!current)return;current.points.push(pt(e));redraw()};
    c.onpointerup=c.onpointercancel=()=>{drawing=false;current=null};
    document.querySelectorAll('[data-draw-sample]').forEach(b=>b.onclick=()=>{praRun.drawSample=b.dataset.drawSample;praRun.drawStrokes=[];renderPraDraw()});
    document.querySelectorAll('[data-draw-color]').forEach(b=>b.onclick=()=>{praRun.drawColor=b.dataset.drawColor;praRun.drawEraser=false;renderPraDraw()});
    document.querySelectorAll('[data-brush-size]').forEach(b=>b.onclick=()=>{praRun.drawSize=+b.dataset.brushSize;renderPraDraw()});
    document.querySelector('#eraserDraw').onclick=()=>{praRun.drawEraser=!praRun.drawEraser;renderPraDraw()};
    document.querySelector('#undoDraw').onclick=()=>{praRun.drawStrokes.pop();renderPraDraw()};
    document.querySelector('#clearDraw').onclick=()=>{praRun.drawStrokes=[];renderPraDraw()};
    document.querySelector('#doneDraw').onclick=()=>praDone('Melukis','✍️',1,1,{sample:sample.name});
  }
  function renderPraColor(){
    praRun.color=praRun.color||'#ff5d73';
    if(!praRun.colorSample){
      praShell('🎨 Pilih gambar untuk mewarna','Pilih satu sample line-art dulu. Lepas tu tap kawasan gambar untuk isi warna.',`<section class="color-card sample-picker-card"><div class="color-sample-grid">${PRA_COLOR_SAMPLES.map(x=>`<button data-color-sample="${x.id}"><span>${x.icon}</span><b>${x.name}</b><small>${x.label}</small></button>`).join('')}</div></section>`);
      document.querySelectorAll('[data-color-sample]').forEach(b=>b.onclick=()=>{praRun.colorSample=b.dataset.colorSample;renderPraColor()});return;
    }
    const sample=PRA_COLOR_SAMPLES.find(x=>x.id===praRun.colorSample)||PRA_COLOR_SAMPLES[0];
    praShell(`🎨 Mewarna · ${sample.label}`,'Pilih warna, kemudian tap mana-mana kawasan putih. Boleh reset atau tukar sample bila-bila masa.',`<section class="color-card"><div class="color-scene">${sample.svg}</div><div class="palette">${[['#ff5d73','Merah'],['#ffbe2e','Kuning'],['#37b86b','Hijau'],['#3d8df5','Biru'],['#8f62de','Ungu'],['#ff8a32','Jingga'],['#8b5a2b','Coklat'],['#ffffff','Putih']].map(([c,n])=>`<button style="--c:${c}" data-paint="${c}" title="${n}" class="${praRun.color===c?'active':''}"><span></span><small>${n}</small></button>`).join('')}</div><div class="color-actions"><button class="soft-btn large" id="changeColorSample">← Tukar Gambar</button><button class="soft-btn large" id="resetColor">Reset</button><button class="start-btn small-start" id="doneColor">Siap Mewarna ✓</button></div></section>`);
    document.querySelectorAll('[data-paint]').forEach(b=>b.onclick=()=>{praRun.color=b.dataset.paint;document.querySelectorAll('[data-paint]').forEach(x=>x.classList.remove('active'));b.classList.add('active')});
    document.querySelectorAll('.paint-region').forEach(el=>el.onclick=()=>el.setAttribute('fill',praRun.color));
    document.querySelector('#resetColor').onclick=()=>document.querySelectorAll('.paint-region').forEach(el=>el.setAttribute('fill',el.dataset.default||'#ffffff'));
    document.querySelector('#changeColorSample').onclick=()=>{praRun.colorSample=null;renderPraColor()};
    document.querySelector('#doneColor').onclick=()=>praDone('Mewarna','🎨',1,1,{sample:sample.label});
  }
  function renderPraMemory(){
    if(!praRun.deck){praRun.deck=P.memoryDeck(6);praRun.open=[];praRun.matched=[];praRun.moves=0}
    const matched=new Set(praRun.matched),open=new Set(praRun.open);
    praShell('🧠 Memory','Cari dua gambar yang sama. Ingat kedudukan kad!',`<section class="memory-card"><div class="memory-status"><b>${matched.size/2}/6 pasangan</b><span>${praRun.moves} cubaan</span></div><div class="memory-grid">${praRun.deck.map((c,i)=>`<button class="memory-tile ${matched.has(i)?'matched':''} ${open.has(i)?'open':''}" data-memory="${i}" ${matched.has(i)?'disabled':''}><span>${matched.has(i)||open.has(i)?c.emoji:'?'}</span></button>`).join('')}</div></section>`);
    document.querySelectorAll('[data-memory]').forEach(b=>b.onclick=()=>memoryPick(+b.dataset.memory));
  }
  function memoryPick(i){if(praRun.open.includes(i)||praRun.matched.includes(i)||praRun.open.length>=2)return;praRun.open.push(i);renderPraMemory();if(praRun.open.length===2){praRun.moves++;const[a,b]=praRun.open;if(praRun.deck[a].key===praRun.deck[b].key){setTimeout(()=>{praRun.matched.push(a,b);praRun.open=[];if(praRun.matched.length===praRun.deck.length)praDone('Memory','🧠',6,6,{moves:praRun.moves});else renderPraMemory()},450)}else setTimeout(()=>{praRun.open=[];renderPraMemory()},700)}}
  function speakPra(word){if(!('speechSynthesis'in window)){toast(`Dengar: ${word}`);return}speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(word);u.lang='ms-MY';u.rate=.72;speechSynthesis.speak(u)}
  function renderPraListen(){
    if(!praRun.items){praRun.items=P.listenSet(5);praRun.i=0;praRun.score=0;praRun.answered=false}if(praRun.i>=praRun.items.length)return praDone('Pendengaran','👂',praRun.score,praRun.items.length);
    const item=praRun.items[praRun.i];praShell('👂 Pendengaran',`Soalan ${praRun.i+1}/${praRun.items.length} · tekan butang bunyi, kemudian pilih jawapan.`,`<section class="listen-card"><button class="listen-play" id="playWord">🔊<b>Dengar perkataan</b></button><div class="listen-options">${item.choices.map((c,i)=>`<button data-listen="${i}" ${praRun.answered?'disabled':''}>${esc(c)}</button>`).join('')}</div><div id="listenFeedback" class="listen-feedback"></div></section>`);document.querySelector('#playWord').onclick=()=>speakPra(item.say);setTimeout(()=>speakPra(item.say),250);document.querySelectorAll('[data-listen]').forEach(b=>b.onclick=()=>{if(praRun.answered)return;praRun.answered=true;const ok=item.choices[+b.dataset.listen]===item.answer;if(ok)praRun.score++;b.classList.add(ok?'correct':'wrong');document.querySelector('#listenFeedback').innerHTML=`<b>${ok?'✅ Betul!':'❌ Jawapan: '+esc(item.answer)}</b><button class="next-btn" id="nextListen">Seterusnya →</button>`;document.querySelector('#nextListen').onclick=()=>{praRun.i++;praRun.answered=false;renderPraListen()};beep(ok)})
  }
  function renderPraOrder(){
    if(!praRun.round){praRun.round=P.orderRound();praRun.roundNo=praRun.roundNo||1;praRun.score=praRun.score||0;praRun.picked=[]}if(praRun.roundNo>5)return praDone('Susun nombor','↕️',praRun.score,5);
    const r=praRun.round;praShell('↕️ Susun nombor',`Pusingan ${praRun.roundNo}/5 · tekan nombor daripada paling kecil ke paling besar.`,`<section class="order-card"><div class="order-picked">${praRun.picked.length?praRun.picked.map(n=>`<span>${n}</span>`).join('<i>→</i>'):'<small>Mula dengan nombor paling kecil</small>'}</div><div class="order-options">${r.choices.map(n=>`<button data-order="${n}" ${praRun.picked.includes(n)?'disabled':''}>${n}</button>`).join('')}</div><div class="order-help" id="orderHelp"></div></section>`);document.querySelectorAll('[data-order]').forEach(b=>b.onclick=()=>orderPick(+b.dataset.order));
  }
  function orderPick(n){const expected=praRun.round.target[praRun.picked.length];if(n!==expected){const h=document.querySelector('#orderHelp');h.textContent='Cuba lagi — cari nombor yang lebih kecil 😊';h.classList.add('bad');beep(false);return}praRun.picked.push(n);beep(true);if(praRun.picked.length===praRun.round.target.length){praRun.score++;setTimeout(()=>{praRun.roundNo++;praRun.round=praRun.roundNo<=5?P.orderRound():null;praRun.picked=[];renderPraOrder()},500)}else renderPraOrder()}


  function learningKey(level=state.prefs.level,subject=state.prefs.subject,topic=state.prefs.topic){return `${level}:${subject}:${topic}`}
  function lessonStatus(level,subject,topic){const k=learningKey(level,subject,topic),m=state.learning.mastery[k];if(m>=80)return {label:'Kuasai',cls:'mastered',icon:'✓'};if(state.learning.completed[k])return {label:'Sudah belajar',cls:'learned',icon:'•'};return {label:'Belum mula',cls:'new',icon:'→'}}
  function learningHub(){
    const p=state.prefs,isPra=p.level==='pra',subs=isPra?[{id:'pra',...C.subjects.pra}]:E.availableSubjects(p.level);
    if(isPra){p.subject='pra'}else if(!subs.some(x=>x.id===p.subject)){p.subject=subs[0]?.id||'bm'}
    const meta=C.subjects[p.subject],topics=meta?.topics||[];if(!topics.includes(p.topic))p.topic=topics[0]||'Campur Semua';save();
    const mastered=topics.filter(t=>(state.learning.mastery[learningKey(p.level,p.subject,t)]||0)>=80).length;
    shell(`<section class="learn-hero"><div><span class="eyebrow light">LEARNING JOURNEY</span><h1>Lihat, gerak, cuba — baru kuasai ✨</h1><p>Belajar guna gambar, objek dan pergerakan. Bila tersalah, Tutor AI akan ajar semula secara visual sebelum beri soalan baharu.</p><div class="journey-mini"><span>👀 Tengok</span><i>›</i><span>🎬 Gerak</span><i>›</i><span>👆 Cuba</span><i>›</i><span>🧠 AI Ajar Semula</span><i>›</i><span>🏆 Kuasai</span></div></div><div class="learn-hero-badge"><b>${mastered}</b><small>topik<br>dikuasai</small></div></section>
    <section class="chooser-block learning-chooser"><div class="step-title"><span>1</span><div><b>Pilih tahap</b><small>Progress belajar disimpan ikut tahap dan topik</small></div></div><div class="level-row">${C.levels.map(l=>`<button class="level-card ${p.level===l.id?'active':''}" data-learn-level="${l.id}"><span>${l.emoji}</span><b>${l.short}</b><small>${l.name}</small></button>`).join('')}</div></section>
    ${!isPra?`<section class="chooser-block learning-chooser"><div class="step-title"><span>2</span><div><b>Pilih subjek</b><small>Masuk satu subjek dan ikut topik satu demi satu</small></div></div><div class="category-subject-grid">${subs.map(x=>`<button class="category-subject subject-bg-${x.id} ${p.subject===x.id?'active':''}" data-learn-pick-sub="${x.id}"><span class="subject-icon subject-${x.id}">${x.emoji}</span><div><b>${esc(x.name)}</b><small>${esc(subjectDesc(x.id))}</small></div><strong>✓</strong></button>`).join('')}</div></section>`:''}
    <section class="chooser-block learning-chooser"><div class="step-title"><span>${isPra?'2':'3'}</span><div><b>Pilih topik untuk belajar</b><small>Tekan topik untuk belajar konsep langkah demi langkah</small></div></div><div class="learning-topic-grid">${topics.map((t,i)=>{const st=lessonStatus(p.level,p.subject,t);return `<button class="learning-topic ${st.cls} ${p.topic===t?'active':''}" data-learn-topic="${esc(t)}"><span class="topic-orb p${i%6}">${i+1}</span><div><b>${esc(t)}</b><small>${st.icon} ${st.label}${state.learning.mastery[learningKey(p.level,p.subject,t)]?` · ${state.learning.mastery[learningKey(p.level,p.subject,t)]}%`:''}</small></div><em>›</em></button>`}).join('')}</div><button class="start-btn learning-start" id="startLesson">Mulakan ${esc(p.topic)} <span>→</span></button></section>`,'learnHub');
    document.querySelectorAll('[data-learn-level]').forEach(b=>b.onclick=()=>{setLevel(b.dataset.learnLevel);if(state.prefs.level!=='pra'){state.prefs.subject=E.availableSubjects(state.prefs.level)[0]?.id||'math';state.prefs.topic=C.subjects[state.prefs.subject]?.topics?.[0]||'Campur Semua'}learningHub()});
    document.querySelectorAll('[data-learn-pick-sub]').forEach(b=>b.onclick=()=>{p.subject=b.dataset.learnPickSub;p.topic=C.subjects[p.subject]?.topics?.[0]||'Campur Semua';save(true);learningHub()});
    document.querySelectorAll('[data-learn-topic]').forEach(b=>b.onclick=()=>{p.topic=b.dataset.learnTopic;save(true);learningHub()});
    document.querySelector('#startLesson').onclick=()=>startLesson(p.topic);
  }
  function tutorSpeak(text){if(!state.settings.sound||!('speechSynthesis'in window)||!text)return;try{speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(String(text));u.lang=lessonRun?.lesson?.subject==='en'?'en-MY':'ms-MY';u.rate=.88;u.pitch=1.02;speechSynthesis.speak(u)}catch{}}
  function adaptiveKey(l){return learningKey(l.level,l.subject,l.topic)}
  function shortLessonText(t,max=105){const x=String(t||'').trim(),first=x.split(/(?<=[.!?])\s+/)[0]||x;return first.length>max?first.slice(0,max).replace(/\s+\S*$/,'')+'…':first}
  function adaptiveStats(l){const k=adaptiveKey(l);return state.learning.adaptive[k]||(state.learning.adaptive[k]={wrong:0,reteach:0,independentCorrect:0,lastAt:0})}
  function freshChallenge(l,attempt=0){return A.makeChallenge(l,attempt)}
  function startLesson(topic=state.prefs.topic){updateStreak();state.prefs.topic=topic;const lesson=L.getLesson(state.prefs.level,state.prefs.subject,topic);lessonRun={lesson,step:0,guidedChallenge:freshChallenge(lesson,0),guidedChoice:null,guidedReteach:false,independentChallenge:freshChallenge(lesson,0),independentChoice:null,reteaching:false,wrongCount:0,correctStreak:0,passed:false};view='lesson';save(true);renderLesson()}
  function lessonHeader(){const r=lessonRun,l=r.lesson,steps=['Tengok','Gerak','Cuba Bersama','Cuba Sendiri','Masteri'];return `<section class="lesson-top"><button class="icon-btn" id="exitLesson">←</button><div class="lesson-title"><small>${esc(levelObj(l.level).name)} · ${esc(C.subjects[l.subject]?.name||'Aktiviti')}</small><b>${l.icon} ${esc(l.title)}</b></div><div class="lesson-step-count">${r.step+1}/5</div></section><div class="lesson-track">${steps.map((x,i)=>`<div class="lesson-node ${i<r.step?'done':i===r.step?'active':''}"><span>${i<r.step?'✓':i+1}</span><small>${x}</small></div>`).join('<i></i>')}</div>`}
  function lessonActions(nextLabel='Seterusnya →',disabled=false){return `<div class="lesson-actions"><button class="soft-btn large" id="lessonBack" ${lessonRun.step===0?'disabled':''}>← Sebelum</button><button class="start-btn small-start" id="lessonNext" ${disabled?'disabled':''}>${nextLabel}</button></div>`}
  function bindLessonActions(){document.querySelector('#exitLesson')?.addEventListener('click',()=>{try{speechSynthesis.cancel()}catch{};lessonRun=null;view='learnHub';render()});document.querySelector('#lessonBack')?.addEventListener('click',()=>{if(lessonRun.step>0){lessonRun.step--;renderLesson()}});document.querySelector('#lessonNext')?.addEventListener('click',()=>{if(lessonRun.step<4){lessonRun.step++;if(lessonRun.step===4){const k=learningKey(lessonRun.lesson.level,lessonRun.lesson.subject,lessonRun.lesson.topic);state.learning.completed[k]=Date.now();save(true)}renderLesson()}})}
  function renderChallengeOptions(ch,selected=null,lock=false){return `<div class="visual-option-grid">${ch.options.map((o,i)=>`<button data-ai-option="${i}" class="${selected!==null?(o.ok?'correct':i===selected?'wrong':'dim'):''}" ${lock?'disabled':''}><span>${esc(o.label)}</span></button>`).join('')}</div>`}
  function renderLesson(){
    if(!lessonRun)return learningHub();const r=lessonRun,l=r.lesson;let body='',activeChallenge=null;
    if(r.step===0){const scene=A.introScene(l);body=`<section class="lesson-card visual-learning-card"><span class="lesson-kicker">👀 TENGOK DULU</span><h1>${esc(l.title)}</h1><p class="tiny-cue">${esc(scene.cue)}</p>${scene.html}<div class="micro-teach"><b>${esc(shortLessonText(l.definition||l.goal))}</b>${l.example?`<small>${esc(shortLessonText(l.example.work||'',80))}</small>`:''}</div><button class="speak-btn" id="speakLesson">🔊 Dengar</button></section>${lessonActions('Lihat pergerakan →')}`}
    if(r.step===1){const demo=A.demoScene(l,1);body=`<section class="lesson-card visual-learning-card"><span class="lesson-kicker">🎬 LIHAT IA BERGERAK</span><h1>Macam ini caranya</h1><p class="tiny-cue">${esc(demo.cue)}</p><div class="ai-demo-stage">${demo.html}</div><div class="step-chips">${(l.steps||[]).slice(0,3).map((x,i)=>`<span><b>${i+1}</b>${esc(String(x.title||'').replace(/^\d+\.\s*/,''))}</span>`).join('')}</div><button class="speak-btn" id="speakLesson">🔊 Dengar</button></section>${lessonActions('Cuba bersama →')}`}
    if(r.step===2){const ch=r.guidedChallenge;activeChallenge=ch;const chosen=r.guidedChoice;const ok=chosen!==null&&ch.options[chosen]?.ok;body=`<section class="lesson-card visual-learning-card"><span class="lesson-kicker">👆 CUBA BERSAMA</span><h1>${esc(ch.prompt)}</h1><button class="speak-btn compact" id="speakChallenge">🔊</button><div class="challenge-visual">${ch.visual}</div>${renderChallengeOptions(ch,chosen,chosen!==null)}${chosen!==null?`<div class="mini-feedback ${ok?'good':'retry'}"><b>${ok?'✅ Betul':'↻ Kita tengok sekali lagi'}</b>${!ok?A.reteachScene(l,ch,1).html:''}</div>`:''}</section>${lessonActions('Cuba tanpa bantuan →',chosen===null||!ok)}`}
    if(r.step===3){const ch=r.independentChallenge;activeChallenge=ch;const stats=adaptiveStats(l);if(r.reteaching){const rt=A.reteachScene(l,ch,r.wrongCount);body=`<section class="lesson-card ai-tutor-card"><div class="ai-tutor-head"><span>🧠</span><div><small>ADAPTIVE VISUAL TUTOR</small><h1>AI ajar semula</h1></div></div><p class="tiny-cue">${esc(rt.cue)}</p><div class="ai-demo-stage reteach">${rt.html}</div><div class="reteach-level"><span class="active">${r.wrongCount===1?'Visual':r.wrongCount===2?'Pecah langkah':'Buat bersama'}</span><small>Tiada jawapan lama akan digunakan semula.</small></div><button class="start-btn" id="tryNewChallenge">Cuba soalan baru →</button></section>${lessonActions('Ke Kuiz Masteri →',true)}`}
      else{const chosen=r.independentChoice,ok=chosen!==null&&ch.options[chosen]?.ok;body=`<section class="lesson-card visual-learning-card independent-card"><div class="independent-top"><div><span class="lesson-kicker">🧠 CUBA TANPA BANTUAN</span><h1>${esc(ch.prompt)}</h1></div><div class="skill-meter"><b>${r.correctStreak}/2</b><small>betul berturut</small></div></div><button class="speak-btn compact" id="speakChallenge">🔊</button><div class="challenge-visual">${ch.visual}</div>${renderChallengeOptions(ch,chosen,chosen!==null)}${chosen!==null?`<div class="mini-feedback ${ok?'good':'retry'}"><b>${ok?(r.passed?'🌟 Dah faham!':'✅ Betul — sekali lagi dengan contoh baru'):'🧠 AI akan ajar semula secara visual'}</b></div>`:''}<div class="adaptive-note">${stats.wrong?`Tutor sudah sesuaikan pembelajaran ${stats.reteach} kali untuk topik ini.`:'AI Tutor perhati cara kamu menjawab — tiada hint dan tiada cheat.'}</div></section>${lessonActions('Ke Kuiz Masteri →',!r.passed)}`}}
    if(r.step===4){const current=state.learning.mastery[learningKey(l.level,l.subject,l.topic)]||0;body=`<section class="lesson-card mastery-ready"><div class="mastery-crown">🏆</div><span class="lesson-kicker">LANGKAH AKHIR</span><h1>${current>=80?'Topik ini sudah dikuasai!':'Sedia untuk Kuiz Masteri?'}</h1><p>${l.subject==='pra'?'Buat aktiviti berkaitan untuk kukuhkan kemahiran.':'10 soalan tanpa bantuan. 80% ke atas dikira kuasai.'}</p><div class="mastery-rule"><span>🎯</span><div><b>Sasaran 80%</b><small>${current?`Skor terbaik: ${current}%`:'Belum ada skor masteri.'}</small></div></div><button class="start-btn" id="launchMastery">${l.subject==='pra'?'Buat Aktiviti Sekarang':'Mula 10 Soalan Masteri'} <span>→</span></button><button class="soft-btn large" id="backLearning">Pilih Topik Lain</button></section>`}
    app.innerHTML=`<main class="lesson-page">${lessonHeader()}<div class="lesson-body">${body}</div></main>`;
    document.querySelector('#exitLesson').onclick=()=>{try{speechSynthesis.cancel()}catch{};lessonRun=null;view='learnHub';render()};bindLessonActions();
    document.querySelector('#speakLesson')?.addEventListener('click',()=>tutorSpeak(l.subject==='en'?(l.definition||l.goal):`${l.title}. ${l.definition||l.goal}`));
    document.querySelector('#speakChallenge')?.addEventListener('click',()=>tutorSpeak(activeChallenge?.speak||activeChallenge?.prompt));
    if(r.step===2){document.querySelectorAll('[data-ai-option]').forEach(b=>b.onclick=()=>{const i=+b.dataset.aiOption;r.guidedChoice=i;const ok=r.guidedChallenge.options[i]?.ok;beep(ok);renderLesson();if(!ok)setTimeout(()=>{if(lessonRun&&lessonRun.step===2){r.guidedChallenge=freshChallenge(l,1);r.guidedChoice=null;renderLesson()}},1150)})}
    if(r.step===3&&!r.reteaching){document.querySelectorAll('[data-ai-option]').forEach(b=>b.onclick=()=>{if(r.independentChoice!==null)return;const i=+b.dataset.aiOption;r.independentChoice=i;const ok=r.independentChallenge.options[i]?.ok,st=adaptiveStats(l);st.lastAt=Date.now();if(ok){r.correctStreak++;st.independentCorrect=(st.independentCorrect||0)+1;r.passed=r.correctStreak>=2;beep(true);save();renderLesson();if(!r.passed)setTimeout(()=>{if(lessonRun&&lessonRun.step===3&&!lessonRun.reteaching){r.independentChallenge=freshChallenge(l,r.wrongCount);r.independentChoice=null;renderLesson()}},700)}else{r.correctStreak=0;r.wrongCount++;st.wrong=(st.wrong||0)+1;st.reteach=(st.reteach||0)+1;r.reteaching=true;beep(false);save(true);setTimeout(()=>renderLesson(),180)}})}
    if(r.step===3&&r.reteaching){document.querySelector('#tryNewChallenge').onclick=()=>{r.reteaching=false;r.independentChoice=null;r.independentChallenge=freshChallenge(l,r.wrongCount);renderLesson()}}
    if(r.step===4){document.querySelector('#backLearning').onclick=()=>{lessonRun=null;view='learnHub';render()};document.querySelector('#launchMastery').onclick=()=>launchMastery(l)}
  }
  function praActivityForTopic(topic){return ({'Kenali Huruf':'letters','Kenali Nombor':'numbers','Lukis':'draw','Mewarna':'color','Ejaan':'spelling','Memory':'memory','Deria & Alam':'senses','Pendengaran':'listen','Susun Nombor':'order','Kira-kira':'counting','Jam & Masa':'time','Campur-campur':'mix'})[topic]||'mix'}
  function launchMastery(l){
    if(l.subject==='pra'){const id=praActivityForTopic(l.topic);state.learning.pendingMastery={key:learningKey(l.level,l.subject,l.topic),level:l.level,subject:l.subject,topic:l.topic};save(true);lessonRun=null;startPraActivity(id);return}
    state.prefs.level=l.level;state.prefs.subject=l.subject;state.prefs.topic=l.topic;state.prefs.mode='exam';state.prefs.count=10;state.prefs.difficulty='auto';state.learning.pendingMastery={key:learningKey(l.level,l.subject,l.topic),level:l.level,subject:l.subject,topic:l.topic};save(true);lessonRun=null;startQuiz();
  }


  async function startQuiz(){
    updateStreak();const p=state.prefs;showLoading('Sediakan latihan…',p.subject==='math'?'Menjana set Matematik baharu.':'Cari soalan curated yang belum dibuat; Smart Generator digunakan bila pool habis.');
    try{const diff=p.mode==='uasa'?'uasa':p.difficulty;const ctx=smartContext(p);const items=await E.makeSet(p.level,p.subject,p.topic,p.count,diff,ctx);quiz={items,i:0,score:0,selected:null,shortValue:'',lastOk:null,answers:[],started:Date.now(),remaining:p.mode==='uasa'?75*60:p.count*45};view='quiz';persistActiveQuiz();hideLoading();renderQuiz();if(state.settings.timer)startTimer()}
    catch(err){hideLoading();toast(err.message||'Gagal memuatkan soalan.');console.error(err)}
  }
  function persistActiveQuiz(){state.activeQuiz=quiz?clone(quiz):null;save(true)}
  function resumeSavedQuiz(){if(!activeQuizResume())return;quiz=clone(state.activeQuiz);view='quiz';renderQuiz();if(state.settings.timer)startTimer()}
  function startTimer(){clearInterval(timerInt);timerInt=setInterval(()=>{if(!quiz)return clearInterval(timerInt);quiz.remaining--;persistActiveQuiz();const el=document.querySelector('#timer');if(el){el.textContent=formatTime(quiz.remaining);el.classList.toggle('warn',quiz.remaining<30)}if(quiz.remaining<=0){clearInterval(timerInt);finishQuiz()}},1000)}

  function clockVisual(item){
    const v=item?.visual;if(!v||v.type!=='clock')return '';
    const hour=Number(v.hour)||12,minute=Number(v.minute)||0,hourAngle=((hour%12)*30)+(minute*.5),minuteAngle=minute*6;
    const nums=Array.from({length:12},(_,i)=>{const n=i+1,a=(n*30-90)*Math.PI/180,x=150+112*Math.cos(a),y=150+112*Math.sin(a);return `<text x="${x.toFixed(1)}" y="${(y+7).toFixed(1)}" text-anchor="middle">${n}</text>`}).join('');
    const ticks=Array.from({length:60},(_,i)=>{const a=i*6*Math.PI/180,major=i%5===0,r1=major?126:132,r2=138,x1=150+r1*Math.sin(a),y1=150-r1*Math.cos(a),x2=150+r2*Math.sin(a),y2=150-r2*Math.cos(a);return `<line x1="${x1.toFixed(1)}" y1="${y1.toFixed(1)}" x2="${x2.toFixed(1)}" y2="${y2.toFixed(1)}" class="${major?'major':'minor'}"/>`}).join('');
    return `<div class="analog-clock-wrap" role="img" aria-label="Jam analog"><svg class="analog-clock" viewBox="0 0 300 300" aria-hidden="true"><circle class="clock-face" cx="150" cy="150" r="145"/>${ticks}${nums}<line class="clock-hand hour" x1="150" y1="150" x2="150" y2="78" transform="rotate(${hourAngle} 150 150)"/><line class="clock-hand minute" x1="150" y1="150" x2="150" y2="48" transform="rotate(${minuteAngle} 150 150)"/><circle class="clock-pin" cx="150" cy="150" r="8"/></svg></div>`;
  }

  function renderQuiz(){
    const p=state.prefs,item=quiz.items[quiz.i],answered=quiz.selected!==null,isLearn=p.mode==='learn',pct=Math.round((quiz.i)/quiz.items.length*100),isShort=item.itemType==='short';
    const sourceLabel=item.smart?'🧠 Smart Generated':item.source==='KPM PBD published example'?'KPM PBD published example':item.alignment||'KPM-aligned';
    app.innerHTML=`<main class="quiz-page"><header class="quiz-top"><button class="icon-btn" id="exitQuiz">←</button><div><small>${esc(levelObj().name)}</small><b>${iconSubject(p.subject)} ${esc(C.subjects[p.subject].name)}</b></div><div class="quiz-counter"><span id="timer" class="timer">${state.settings.timer?formatTime(quiz.remaining):`${quiz.i+1}/${quiz.items.length}`}</span></div></header><div class="quiz-progress"><i style="width:${pct}%"></i></div><section class="quiz-card"><div class="quiz-meta"><span>${esc(item.topic)}</span><span>${esc(modeLabel(p.mode))}</span><span class="source-pill">${esc(sourceLabel)}</span></div><h1>${esc(item.question)}</h1>${clockVisual(item)}${isShort?`<div class="short-answer-wrap"><label>Jawapan anda</label><input id="shortAnswer" class="short-answer-input" autocomplete="off" inputmode="text" ${answered?'disabled':''} value="${answered?esc(quiz.shortValue||''):''}"><button class="start-btn small-start" id="submitShort" ${answered?'disabled':''}>Hantar Jawapan</button></div>`:`<div class="answer-list">${item.answers.map((a,idx)=>{let cls='';if(answered&&isLearn){if(String(a)===String(item.correct))cls='correct';else if(idx===quiz.selected)cls='wrong';else cls='dim'}return `<button class="answer-btn ${cls}" data-answer="${idx}" ${answered&&isLearn?'disabled':''}><span>${String.fromCharCode(65+idx)}</span><b>${esc(a)}</b>${answered&&isLearn&&String(a)===String(item.correct)?'<em>✓</em>':''}</button>`}).join('')}</div>`}${answered&&isLearn?`<div class="feedback-box ${quiz.lastOk?'good':'bad'}"><b>${quiz.lastOk?'✅ Betul!':'❌ Belum tepat'}</b><p>${esc(item.explanation||'')}</p>${isShort&&!quiz.lastOk?`<small>Jawapan yang diterima: <b>${esc(item.correct)}</b></small>`:''}</div><button class="next-btn" id="nextQ">${quiz.i===quiz.items.length-1?'Lihat Keputusan':'Seterusnya →'}</button>`:''}</section></main>`;
    document.querySelector('#exitQuiz').onclick=()=>{persistActiveQuiz();quiz=null;view='home';render();toast('Sesi disimpan. Boleh sambung kemudian.')};
    document.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>answer(+b.dataset.answer));
    const inp=document.querySelector('#shortAnswer');if(inp&&!answered){inp.focus();inp.addEventListener('keydown',e=>{if(e.key==='Enter')submitShortAnswer()})}
    document.querySelector('#submitShort')?.addEventListener('click',submitShortAnswer);document.querySelector('#nextQ')?.addEventListener('click',nextQ);
  }
  function answer(idx){if(quiz.selected!==null&&state.prefs.mode==='learn')return;const item=quiz.items[quiz.i],chosen=item.answers[idx],ok=String(chosen)===String(item.correct);quiz.selected=idx;quiz.lastOk=ok;if(ok)quiz.score++;quiz.answers.push({id:item.id,q:item.question,chosen:String(chosen),correct:String(item.correct),ok,topic:item.topic,subject:state.prefs.subject,explanation:item.explanation,source:item.source,alignment:item.alignment,itemType:item.itemType||'mcq',smart:!!item.smart,smartSignature:item.smartSignature||''});persistActiveQuiz();if(state.prefs.mode==='learn'){beep(ok);renderQuiz()}else nextQ()}
  function shortCorrect(input,item){const a=E.normalizeAnswer(input),b=E.normalizeAnswer(item.correct);if(a===b)return true;const na=parseFloat(a.replace(/[^0-9.\-]/g,'')),nb=parseFloat(b.replace(/[^0-9.\-]/g,''));return Number.isFinite(na)&&Number.isFinite(nb)&&na===nb}
  function submitShortAnswer(){if(quiz.selected!==null&&state.prefs.mode==='learn')return;const item=quiz.items[quiz.i],input=(document.querySelector('#shortAnswer')?.value||'').trim();if(!input){toast('Masukkan jawapan dulu');return}const ok=shortCorrect(input,item);quiz.selected=-1;quiz.shortValue=input;quiz.lastOk=ok;if(ok)quiz.score++;quiz.answers.push({id:item.id,q:item.question,chosen:input,correct:String(item.correct),ok,topic:item.topic,subject:state.prefs.subject,explanation:item.explanation,source:item.source,alignment:item.alignment,itemType:'short',smart:!!item.smart,smartSignature:item.smartSignature||''});persistActiveQuiz();if(state.prefs.mode==='learn'){beep(ok);renderQuiz()}else nextQ()}
  function nextQ(){if(quiz.i>=quiz.items.length-1)return finishQuiz();quiz.i++;quiz.selected=null;quiz.shortValue='';quiz.lastOk=null;persistActiveQuiz();renderQuiz()}
  function finishQuiz(){
    clearInterval(timerInt);if(!quiz)return;const p=state.prefs,total=quiz.items.length,score=quiz.score,pct=Math.round(score/total*100),xp=score*10+(pct===100?50:0);state.xp+=xp;state.answers+=total;state.correct+=score;recordSmartProgress(p,quiz.answers);const now=new Date();state.sessions.unshift({date:now.toLocaleDateString('ms-MY'),day:dayKey(now),ts:Date.now(),level:p.level,subject:p.subject,topic:p.topic,difficulty:p.difficulty,mode:p.mode,score,total,pct,answers:quiz.answers});state.sessions=state.sessions.slice(0,100);const masteryPending=state.learning.pendingMastery;if(masteryPending){const prev=state.learning.mastery[masteryPending.key]||0;state.learning.mastery[masteryPending.key]=Math.max(prev,pct);if(pct>=80)state.learning.completed[masteryPending.key]=Date.now();state.learning.pendingMastery=null;}quiz.result={score,total,pct,xp,answers:quiz.answers,mastery:!!masteryPending,masteryTopic:masteryPending?.topic||''};state.activeQuiz=null;save(true);view='result';beep(pct>=60);renderResult();
  }
  function renderResult(){
    const r=quiz.result,msg=r.pct===100?'Cemerlang! 🌟':r.pct>=80?'Hebat! 👏':r.pct>=60?'Bagus, teruskan! 💪':'Jom cuba lagi 📚',weak=[...new Set(r.answers.filter(a=>!a.ok).map(a=>a.topic))];
    app.innerHTML=`<main class="result-page"><section class="result-card"><div class="result-icon">${r.pct>=80?'🏆':'🎯'}</div><small>KEPUTUSAN</small><h1>${msg}</h1><div class="result-score">${r.pct}%</div><p>${r.score} betul daripada ${r.total} soalan · +${r.xp} XP</p>${r.mastery?`<div class="mastery-result ${r.pct>=80?'pass':'retry'}"><b>${r.pct>=80?'🏆 Topik Dikuasai':'📚 Hampir sampai'}</b><span>${r.pct>=80?`${esc(r.masteryTopic)} sudah mencapai tahap masteri.`:'Ulang bahagian Belajar atau cuba set baharu untuk capai 80%.'}</span></div>`:''}<div class="result-actions"><button class="start-btn" id="retry">Cuba Set Baru</button><button class="soft-btn large" id="backHome">Balik Utama</button></div></section>${weak.length?`<section class="review-summary"><b>Topik untuk ulang kaji</b><div class="topic-list">${weak.map(w=>`<span class="topic active-soft">${esc(w)}</span>`).join('')}</div></section>`:''}<section class="answer-review"><div class="section-title"><div><small>SEMAKAN</small><h2>Jawapan anda</h2></div></div>${r.answers.map((a,i)=>`<div class="review-row ${a.ok?'ok':'no'}"><span>${a.ok?'✓':'!'}</span><div><small>${i+1}. ${esc(a.topic)}</small><b>${esc(a.q)}</b><p>Jawapan anda: ${esc(a.chosen)}${a.ok?'':` · Betul: ${esc(a.correct)}`}</p><small class="review-source">${esc(a.source||'LatihKu Original')} · ${esc(a.alignment||'KPM-aligned')}</small>${!a.ok?`<em>${esc(a.explanation||'')}</em>`:''}</div></div>`).join('')}</section>${nav('progress')}</main>`;
    bindCommon();document.querySelector('#retry').onclick=startQuiz;document.querySelector('#backHome').onclick=()=>{quiz=null;view='home';render()};
  }

  function progress(){
    const sessions=state.sessions,pct=state.answers?Math.round(state.correct/state.answers*100):0,bySubject={};sessions.forEach(s=>{bySubject[s.subject]??={n:0,c:0,t:0};bySubject[s.subject].n++;bySubject[s.subject].c+=s.score;bySubject[s.subject].t+=s.total});
    const wrongTopics={};sessions.forEach(s=>(s.answers||[]).filter(a=>!a.ok).forEach(a=>{const key=`${s.subject}|${a.topic}`;wrongTopics[key]=(wrongTopics[key]||0)+1}));const weak=Object.entries(wrongTopics).sort((a,b)=>b[1]-a[1]).slice(0,6);
    shell(`<section class="practice-header"><span class="eyebrow">PRESTASI ${esc(state.profile.name).toUpperCase()}</span><h1>Progress pembelajaran</h1><p>Nampak terus apa yang dah kuat dan topik mana patut ulang.</p></section><section class="stats-row wide"><div class="metric-card"><span>🎯</span><div><small>Ketepatan keseluruhan</small><b>${pct}%</b></div></div><div class="metric-card"><span>✅</span><div><small>Jumlah soalan</small><b>${state.answers}</b></div></div><div class="metric-card"><span>📚</span><div><small>Jumlah sesi</small><b>${sessions.length}</b></div></div></section>
    <section class="content-section"><div class="section-title"><div><small>SUBJEK</small><h2>Prestasi mengikut subjek</h2></div></div>${Object.keys(bySubject).length?`<div class="performance-grid">${Object.entries(bySubject).map(([id,v])=>{const p=Math.round(v.c/v.t*100);return `<div class="performance-card"><span class="subject-icon subject-${id}">${iconSubject(id)}</span><div><b>${esc(C.subjects[id]?.name)}</b><small>${v.n} sesi · ${p}% tepat</small><i><em style="width:${p}%"></em></i></div><strong>${p}%</strong></div>`}).join('')}</div>`:`<div class="empty-card">Belum ada rekod. Buat satu latihan dulu 😊</div>`}</section>
    <section class="content-section"><div class="section-title"><div><small>FOKUS</small><h2>Topik perlu ulang</h2></div></div><div class="focus-card">${weak.length?weak.map(([key,n])=>{const [sub,topic]=key.split('|');return `<div class="focus-row"><span class="subject-icon subject-${sub}">${iconSubject(sub)}</span><div><b>${esc(topic)}</b><small>${esc(C.subjects[sub]?.name)} · tersalah ${n} kali</small></div><strong>Ulang</strong></div>`}).join(''):'<div class="empty-inline">Belum cukup data untuk kenal pasti topik lemah.</div>'}</div></section>
    <section class="content-section"><div class="section-title"><div><small>SEJARAH</small><h2>Latihan terkini</h2></div></div><div class="history-card">${sessions.length?sessions.slice(0,15).map(s=>`<div class="history-line"><span class="subject-icon subject-${s.subject}">${iconSubject(s.subject)}</span><div><b>${esc(C.subjects[s.subject]?.name)}</b><small>${esc(levelObj(s.level).short)} · ${esc(s.topic)} · ${esc(s.date)}</small></div><strong>${s.pct}%</strong></div>`).join(''):'<div class="empty-inline">Tiada sesi lagi.</div>'}</div></section>`,'progress');
  }

  async function settings(){
    const downloaded=state.settings.offlineDownloadedAt,bank=E.totalStatic().toLocaleString('ms-MY');
    shell(`<section class="practice-header"><span class="eyebrow">TETAPAN</span><h1>Profil & aplikasi</h1><p>Semua benda penting, tanpa menu yang berserabut.</p></section><section class="settings-card"><label>Nama pelajar<input id="studentName" class="name-input compact" maxlength="20" value="${esc(state.profile.name)}"></label><div class="avatar-label">Sticker profil</div><div class="avatar-picker compact">${AVATARS.map(a=>`<button class="avatar-choice ${state.profile.avatar===a?'active':''}" data-avatar-edit="${a}">${a}</button>`).join('')}</div></section>
    <section class="settings-card"><div class="setting-line"><div><b>🔊 Bunyi feedback</b><small>Bunyi ringkas selepas jawab.</small></div><button class="toggle ${state.settings.sound?'on':''}" data-toggle="sound"><i></i></button></div><div class="setting-line"><div><b>⏱️ Timer</b><small>45 saat setiap soalan.</small></div><button class="toggle ${state.settings.timer?'on':''}" data-toggle="timer"><i></i></button></div><div class="setting-line"><div><b>📱 Pasang aplikasi</b><small>Add to Home Screen.</small></div><button class="soft-btn" id="installSettings">Pasang</button></div></section>
    <section class="settings-card"><div class="section-title"><div><small>OFFLINE</small><h2>Bank soalan</h2></div><span>${bank}+ soalan</span></div><p>${formatBytes(E.totalBytes())} data static. ${downloaded?`✅ Pernah download: ${esc(downloaded)}`:'Download semua sekali untuk akses penuh tanpa internet.'}</p><div class="offline-progress hidden" id="offlineProgress"><div><span id="offlineLabel">0 / 40 pek</span><b id="offlinePct">0%</b></div><i><em id="offlineBar" style="width:0%"></em></i></div><div class="setting-buttons"><button class="start-btn small-start" id="downloadAll">Download Semua</button><button class="soft-btn large" id="clearCache">Kosongkan Cache</button></div></section>
    <section class="settings-card"><div class="section-title"><div><small>RUJUKAN</small><h2>KPM-aligned Learning + Practice</h2></div><span>v17 · Adaptive Visual Tutor</span></div><p><b>👀 Learning Engine v17:</b> pembelajaran kini visual-first: tengok gambar/objek, lihat pergerakan, cuba bersama dan cuba sendiri. Teks dipendekkan; butang audio ringkas digunakan apabila speech synthesis peranti tersedia.</p><p><b>🧠 Adaptive Visual Tutor:</b> tiada Hint/Cheat. Jika murid salah dalam Cuba Sendiri, tutor automatik ajar semula dengan visual dan animation, kemudian beri soalan baharu. Murid perlu 2 jawapan betul berturut-turut sebelum ke Mastery.</p><p><b>🧠 Smart Practice:</b> soalan curated yang belum pernah dibuat digunakan dahulu. Selepas pool habis, Smart Generator menghasilkan variasi baharu secara offline dan fokus lebih kepada topik yang kerap salah.</p></section>
    <section class="settings-card"><div class="section-title"><div><small>DATA</small><h2>Backup progress</h2></div></div><p>Progress v17 disimpan dalam localStorage + IndexedDB. Backup berguna kalau tukar phone atau clear browser data.</p><div class="setting-buttons"><button class="soft-btn large" id="backupBtn">⬇ Backup</button><button class="soft-btn large" id="restoreBtn">⬆ Restore</button><button class="danger-btn" id="resetData">Reset Progress</button></div></section>`,'settings');
    document.querySelector('#studentName').onchange=e=>{state.profile.name=e.target.value.trim()||state.profile.name;save(true);settings()};
    document.querySelectorAll('[data-avatar-edit]').forEach(b=>b.onclick=()=>{state.profile.avatar=b.dataset.avatarEdit;save(true);settings()});
    document.querySelectorAll('[data-toggle]').forEach(b=>b.onclick=()=>{state.settings[b.dataset.toggle]=!state.settings[b.dataset.toggle];save(true);settings()});
    document.querySelector('#installSettings').onclick=installApp;document.querySelector('#downloadAll').onclick=downloadAllOffline;document.querySelector('#clearCache').onclick=clearDataCache;document.querySelector('#backupBtn').onclick=exportBackup;document.querySelector('#restoreBtn').onclick=()=>restoreFile.click();
    document.querySelector('#resetData').onclick=()=>{if(confirm('Reset semua progress dan mula semula?')){state=clone(defaults);onboardStep=1;localStorage.removeItem(STORAGE_KEY);idbSave(state).catch(()=>{});save(true);toast('Progress direset');view='home';render()}};
  }

  function exportBackup(){const payload={app:'LatihKu Study',version:C.version,exportedAt:new Date().toISOString(),state};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`LatihKu-backup-${dayKey()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('Backup siap ✅')}
  restoreFile.onchange=async e=>{const f=e.target.files?.[0];if(!f)return;try{const data=JSON.parse(await f.text());if(!data.state)throw new Error('Fail backup tak sah');if(!confirm('Restore backup ini? Progress semasa akan diganti.'))return;state=migrate(data.state);state.profile.onboarded=!!state.profile.name;onboardStep=state.profile.name?2:1;save(true);toast('Progress berjaya dipulihkan ✅');view='home';render()}catch(err){toast(err.message||'Backup tak sah')}finally{e.target.value=''}};
  async function downloadAllOffline(){const box=document.querySelector('#offlineProgress'),bar=document.querySelector('#offlineBar'),label=document.querySelector('#offlineLabel'),pct=document.querySelector('#offlinePct'),btn=document.querySelector('#downloadAll');box.classList.remove('hidden');btn.disabled=true;btn.textContent='Downloading…';try{await E.downloadAll((done,total)=>{const p=Math.round(done/total*100);bar.style.width=`${p}%`;label.textContent=`${done} / ${total} pek`;pct.textContent=`${p}%`});state.settings.offlineDownloadedAt=new Date().toLocaleString('ms-MY');save(true);toast('Semua bank soalan siap offline ✅');setTimeout(settings,400)}catch(err){toast(`Download tak lengkap: ${err.message}`);btn.disabled=false;btn.textContent='Cuba Lagi'}}
  async function clearDataCache(){if(!confirm('Kosongkan cache soalan? Progress tak akan dipadam.'))return;E.clearMemory();state.settings.offlineDownloadedAt='';save(true);if('serviceWorker'in navigator){const reg=await navigator.serviceWorker.ready;reg.active?.postMessage({type:'CLEAR_DATA_CACHE'})}toast('Cache dikosongkan');settings()}
  function installApp(){if(installPrompt){installPrompt.prompt();installPrompt.userChoice.finally(()=>installPrompt=null);return}const ios=/iphone|ipad|ipod/i.test(navigator.userAgent);toast(ios?'Safari: Share → Add to Home Screen':'Browser menu → Install app / Add to Home Screen')}
  function bindInstall(){document.querySelector('#installBtn')?.addEventListener('click',installApp)}
  function render(){clearInterval(timerInt);if(!state.profile.onboarded||!state.profile.name)return onboard();if(view==='home')home();else if(view==='learnHub')learningHub();else if(view==='lesson'&&lessonRun)renderLesson();else if(view==='practice')practice();else if(view==='praSpecial'&&praRun)renderPraSpecial();else if(view==='progress')progress();else if(view==='settings')settings();else if(view==='quiz'&&quiz)renderQuiz();else home();bindInstall()}
  window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e});window.addEventListener('appinstalled',()=>toast('LatihKu berjaya dipasang 🎉'));window.addEventListener('beforeunload',()=>save(true));document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='hidden')save(true)});if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('sw.js').catch(console.error));
  render();hydrateMirror();
})();
