(() => {
  const C=window.LATIH_CONFIG,E=window.LATIH_ENGINE,P=window.LATIH_PRA;
  const app=document.querySelector('#app'),toastEl=document.querySelector('#toast'),loading=document.querySelector('#loading'),loadingTitle=document.querySelector('#loadingTitle'),loadingText=document.querySelector('#loadingText'),restoreFile=document.querySelector('#restoreFile');
  const STORAGE_KEY='latihkuStudyV9';
  const AVATARS=['🧒','👦','👧','🧑‍🚀','👩‍🔬','🧑‍🎨'];
  const defaults={
    schemaVersion:9,meta:{updatedAt:0},profile:{name:'',avatar:'🧒',onboarded:false},
    xp:0,streak:0,lastDay:'',sessions:[],answers:0,correct:0,
    settings:{sound:true,timer:false,offlineDownloadedAt:'',persistentStorage:false},
    prefs:{level:'1',subject:'math',topic:'Campur Semua',mode:'learn',count:10,difficulty:'auto',praActivity:'mix'},
    activeQuiz:null
  };
  let state=load(),view='home',quiz=null,praRun=null,installPrompt=null,timerInt=null,saveTimer=null;

  function clone(x){return JSON.parse(JSON.stringify(x))}
  function merge(a,b){const o=clone(a);for(const k in (b||{})){o[k]=(b[k]&&typeof b[k]==='object'&&!Array.isArray(b[k]))?merge(o[k]||{},b[k]):b[k]}return o}
  function migrate(s){const m=merge(defaults,s||{});m.schemaVersion=9;if(!m.profile)m.profile=clone(defaults.profile);if(!m.meta)m.meta={updatedAt:0};return m}
  function load(){try{return migrate(JSON.parse(localStorage.getItem(STORAGE_KEY)||'{}'))}catch{return clone(defaults)}}
  function save(immediate=false){state.meta.updatedAt=Date.now();const run=()=>{try{localStorage.setItem(STORAGE_KEY,JSON.stringify(state))}catch{};idbSave(state).catch(()=>{})};if(immediate){clearTimeout(saveTimer);run()}else{clearTimeout(saveTimer);saveTimer=setTimeout(run,80)}}
  function openDB(){return new Promise((resolve,reject)=>{if(!('indexedDB'in window))return reject(new Error('No IndexedDB'));const r=indexedDB.open('LatihKuStudyDB',1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains('state'))r.result.createObjectStore('state')};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
  async function idbSave(data){const db=await openDB();return new Promise((res,rej)=>{const tx=db.transaction('state','readwrite');tx.objectStore('state').put(clone(data),'main');tx.oncomplete=()=>{db.close();res()};tx.onerror=()=>rej(tx.error)})}
  async function idbLoad(){const db=await openDB();return new Promise((res,rej)=>{const tx=db.transaction('state','readonly'),r=tx.objectStore('state').get('main');r.onsuccess=()=>{db.close();res(r.result||null)};r.onerror=()=>rej(r.error)})}
  async function hydrateMirror(){try{const m=await idbLoad();if(m?.meta?.updatedAt>state.meta.updatedAt){state=migrate(m);localStorage.setItem(STORAGE_KEY,JSON.stringify(state));render()}else{idbSave(state).catch(()=>{})}}catch{}}

  function esc(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
  function toast(m){toastEl.textContent=m;toastEl.classList.add('show');setTimeout(()=>toastEl.classList.remove('show'),2200)}
  function showLoading(title='Memuatkan…',text=''){loadingTitle.textContent=title;loadingText.textContent=text;loading.classList.remove('hidden')}
  function hideLoading(){loading.classList.add('hidden')}
  function dayKey(d=new Date()){return `${d.getFullYear()}-${d.getMonth()+1}-${d.getDate()}`}
  function levelObj(id=state.prefs.level){return C.levels.find(x=>x.id===id)||C.levels[1]}
  function subObj(id=state.prefs.subject){return C.subjects[id]||C.subjects.math}
  function iconSubject(id){return C.subjects[id]?.emoji||'📚'}
  function formatBytes(bytes){if(bytes<1024)return `${bytes} B`;if(bytes<1024**2)return `${(bytes/1024).toFixed(1)} KB`;return `${(bytes/1024**2).toFixed(1)} MB`}
  function formatTime(s){const m=Math.floor(Math.max(0,s)/60),r=Math.max(0,s)%60;return `${m}:${String(r).padStart(2,'0')}`}
  function beep(ok=true){if(!state.settings.sound)return;try{const A=window.AudioContext||window.webkitAudioContext,ctx=new A(),osc=ctx.createOscillator(),gain=ctx.createGain();osc.type='sine';osc.frequency.value=ok?690:230;gain.gain.value=.025;osc.connect(gain);gain.connect(ctx.destination);osc.start();osc.stop(ctx.currentTime+.08);osc.onended=()=>ctx.close()}catch{}}
  function todayStats(){const t=dayKey(),ss=state.sessions.filter(s=>s.day===t),total=ss.reduce((a,s)=>a+s.total,0),correct=ss.reduce((a,s)=>a+s.score,0);return{sessions:ss.length,total,correct,pct:total?Math.round(correct/total*100):0}}
  function updateStreak(){const t=dayKey();if(state.lastDay===t)return;const y=new Date();y.setDate(y.getDate()-1);state.streak=state.lastDay===dayKey(y)?state.streak+1:1;state.lastDay=t}
  function activeQuizResume(){return state.activeQuiz?.items?.length&&state.activeQuiz.i<state.activeQuiz.items.length}

  function onboard(){
    app.innerHTML=`<main class="welcome-page"><section class="welcome-card"><div class="welcome-visual"><div class="logo-bubble">📚</div><div class="spark s1">✦</div><div class="spark s2">✦</div><div class="spark s3">★</div><h1>LatihKu</h1><p>Belajar ikut tahap, subjek dan topik — ringkas, kemas dan terus mula.</p><div class="mini-books"><span>🔢</span><span>📖</span><span>🔬</span><span>🔤</span></div></div><div class="welcome-form"><span class="eyebrow">SELAMAT DATANG</span><h2>Siapa nama anda?</h2><p>Tak perlu login. Nama dan progress disimpan dalam peranti ini.</p><input id="firstName" class="name-input" maxlength="20" autocomplete="off" placeholder="Contoh: Aiman" value="${esc(state.profile.name)}"><div class="avatar-label">Pilih avatar</div><div class="avatar-picker">${AVATARS.map(a=>`<button class="avatar-choice ${state.profile.avatar===a?'active':''}" data-avatar="${a}">${a}</button>`).join('')}</div><button class="primary-cta" id="beginBtn">Mula Belajar <span>→</span></button><small class="privacy-line">🔒 Tiada akaun · Tiada iklan · Progress local</small></div></section></main>`;
    document.querySelectorAll('[data-avatar]').forEach(b=>b.onclick=()=>{state.profile.avatar=b.dataset.avatar;save();onboard()});
    const input=document.querySelector('#firstName');input.focus();
    document.querySelector('#beginBtn').onclick=()=>{const n=input.value.trim();if(!n){input.classList.add('shake');setTimeout(()=>input.classList.remove('shake'),450);return}state.profile.name=n;state.profile.onboarded=true;save(true);view='home';render()};
    input.addEventListener('keydown',e=>{if(e.key==='Enter')document.querySelector('#beginBtn').click()});
  }

  function nav(active){return `<nav class="bottomnav">${[['home','⌂','Utama'],['practice','✎','Latihan'],['progress','▥','Prestasi'],['settings','⚙','Tetapan']].map(([id,ic,n])=>`<button class="navbtn ${active===id?'active':''}" data-view="${id}"><span>${ic}</span><b>${n}</b></button>`).join('')}</nav>`}
  function topbar(){return `<header class="topbar"><button class="student-chip" data-view="settings"><span class="student-avatar">${state.profile.avatar}</span><span><small>Hai,</small><b>${esc(state.profile.name)}</b></span></button><div class="top-stats"><span>🔥 <b>${state.streak}</b></span><span>⭐ <b>${state.xp}</b></span></div></header>`}
  function shell(content,active=view){app.innerHTML=`<main class="app">${topbar()}<div class="page">${content}</div>${nav(active)}</main>`;bindCommon()}
  function bindCommon(){document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{view=b.dataset.view;quiz=null;render()})}
  function installBanner(){if(matchMedia('(display-mode: standalone)').matches)return '';return `<div class="install-banner"><div><b>📱 Pasang LatihKu</b><small>Guna macam app biasa dan lebih mudah buka setiap hari.</small></div><button class="soft-btn" id="installBtn">Pasang</button></div>`}


  function subjectDesc(id){return ({math:'Nombor, operasi, wang, masa & bentuk',bm:'Kefahaman, tatabahasa, kosa kata & ejaan',en:'Vocabulary, grammar & comprehension',sci:'Manusia, haiwan, tumbuhan, bahan & tenaga',hist:'Sejarah Malaysia, tokoh & zaman',islam:'Akidah, ibadah, sirah, akhlak & Jawi',moral:'Nilai, tanggungjawab & hubungan sosial',pjpk:'Kecergasan, kesihatan & keselamatan',pra:'Aktiviti awal sebelum Tahun 1'})[id]||'Latihan mengikut topik';}
  function setLevel(id){state.prefs.level=id;const subs=E.availableSubjects(id);state.prefs.subject=subs[0]?.id||'math';state.prefs.topic='Campur Semua';if(id==='pra')state.prefs.praActivity=state.prefs.praActivity||'mix';save(true);}
  function praTiles(){return `<div class="pra-activity-grid">${P.activities.map(a=>`<button class="pra-activity ${a.accent}" data-pra="${a.id}"><span>${a.icon}</span><div><b>${esc(a.name)}</b><small>${esc(a.desc)}</small></div><em>›</em></button>`).join('')}</div>`}
  function home(){
    const today=todayStats(),recent=state.sessions[0],bank=E.totalStatic().toLocaleString('ms-MY'),subs=E.availableSubjects(state.prefs.level),isPra=state.prefs.level==='pra';
    const categories=isPra?praTiles():`<div class="quick-subject-grid rich">${subs.map(s=>`<button class="quick-subject rich-card" data-quick-subject="${s.id}"><span class="subject-icon subject-${s.id}">${s.emoji}</span><div><b>${esc(s.name)}</b><small>${esc(subjectDesc(s.id))}</small></div><strong>›</strong></button>`).join('')}</div>`;
    shell(`${installBanner()}<section class="home-hero"><div class="hero-copy"><span class="eyebrow light">${esc(levelObj().name).toUpperCase()}</span><h1>Jom belajar, ${esc(state.profile.name)}! 👋</h1><p>${isPra?'Pilih aktiviti ceria — bukan peperiksaan formal. Ada huruf, nombor, lukis, mewarna, memory dan banyak lagi.':'Pilih subjek dan topik. Mode Belajar bagi feedback terus; Mode Ujian semak di hujung.'}</p><div class="hero-buttons"><button class="hero-primary" id="heroStart">${isPra?'Pilih Aktiviti':'Mula Latihan'}</button>${activeQuizResume()?'<button class="hero-secondary" id="resumeQuiz">Sambung Sesi</button>':''}</div></div><div class="hero-art"><div class="book-stack"><span>${isPra?'🎨':'📘'}</span><span>${isPra?'🔤':'📗'}</span><span>${isPra?'🧠':'📙'}</span></div><div class="hero-star">★</div></div></section>
    <section class="content-section"><div class="section-title"><div><small>TAHAP</small><h2>Pilih tahap</h2></div></div><div class="home-level-row">${C.levels.map(l=>`<button class="home-level ${state.prefs.level===l.id?'active':''}" data-home-level="${l.id}"><span>${l.emoji}</span><b>${l.short}</b><small>${l.name}</small></button>`).join('')}</div></section>
    <section class="stats-row"><div class="metric-card"><span>🎯</span><div><small>Ketepatan hari ini</small><b>${today.pct}%</b></div></div><div class="metric-card"><span>✅</span><div><small>Aktiviti/soalan hari ini</small><b>${today.total}</b></div></div><div class="metric-card"><span>🔥</span><div><small>Streak</small><b>${state.streak} hari</b></div></div></section>
    <section class="content-section"><div class="section-title"><div><small>${isPra?'AKTIVITI PRA':'SUBJEK'}</small><h2>${isPra?'Pilih corak aktiviti':'Pilih kategori belajar'}</h2></div><span>${isPra?'12 aktiviti':`${bank}+ soalan`}</span></div>${categories}</section>
    ${!isPra?`<section class="content-section"><div class="simple-note kpm-note"><b>📘 Rujukan pentaksiran</b><span>Latihan original. Untuk Tahun 4–6, Mode Ujian + Auto menggunakan agihan aras 5:3:2 sebagai rujukan format UASA KPM; ia bukan kertas rasmi KPM.</span></div></section>`:`<section class="content-section"><div class="simple-note kpm-note"><b>🧒 Pra Sekolah</b><span>Fokus pada aktiviti dan hasil kerja — bukan peperiksaan formal. Mewarna, lukis, memory dan pendengaran boleh dibuat terus dalam app.</span></div></section>`}
    ${recent?`<section class="content-section"><div class="section-title"><div><small>TERKINI</small><h2>Sesi terakhir</h2></div></div><div class="recent-card"><span class="subject-icon subject-${recent.subject}">${iconSubject(recent.subject)}</span><div><b>${esc(C.subjects[recent.subject]?.name||'Aktiviti')}</b><small>${esc(levelObj(recent.level).name)} · ${esc(recent.topic)}</small></div><strong>${recent.pct}%</strong></div></section>`:''}`,'home');
    document.querySelector('#heroStart').onclick=()=>{view='practice';render()};
    document.querySelector('#resumeQuiz')?.addEventListener('click',resumeSavedQuiz);
    document.querySelectorAll('[data-home-level]').forEach(b=>b.onclick=()=>{setLevel(b.dataset.homeLevel);home()});
    document.querySelectorAll('[data-quick-subject]').forEach(b=>b.onclick=()=>{state.prefs.subject=b.dataset.quickSubject;state.prefs.topic='Campur Semua';save(true);view='practice';render()});
    document.querySelectorAll('[data-pra]').forEach(b=>b.onclick=()=>startPraActivity(b.dataset.pra));
    bindInstall();
  }

  function practice(){
    const p=state.prefs,subs=E.availableSubjects(p.level);if(!subs.some(s=>s.id===p.subject)){p.subject=subs[0].id;p.topic='Campur Semua'}
    if(p.level==='pra'){
      shell(`<section class="practice-header"><span class="eyebrow">PRA SEKOLAH</span><h1>Main sambil belajar</h1><p>Pilih satu aktiviti. Untuk Pra, kita utamakan interaksi, pemerhatian dan hasil kerja — bukan peperiksaan formal.</p></section>
      <section class="chooser-block"><div class="step-title"><span>1</span><div><b>Pilih tahap</b><small>Boleh tukar ke Tahun 1–6 bila-bila masa</small></div></div><div class="level-row">${C.levels.map(l=>`<button class="level-card ${p.level===l.id?'active':''}" data-level="${l.id}"><span>${l.emoji}</span><b>${l.short}</b><small>${l.name}</small></button>`).join('')}</div></section>
      <section class="chooser-block"><div class="step-title"><span>2</span><div><b>Pilih corak aktiviti</b><small>Macam menu aktiviti kanak-kanak — tekan dan terus mula</small></div></div>${praTiles()}</section>`,'practice');
      document.querySelectorAll('[data-level]').forEach(x=>x.onclick=()=>{setLevel(x.dataset.level);practice()});
      document.querySelectorAll('[data-pra]').forEach(b=>b.onclick=()=>startPraActivity(b.dataset.pra));return;
    }
    const meta=C.subjects[p.subject],topics=['Campur Semua',...meta.topics];if(!topics.includes(p.topic))p.topic='Campur Semua';save();
    const uasaAuto=p.mode==='exam'&&+p.level>=4&&p.difficulty==='auto';
    shell(`<section class="practice-header"><span class="eyebrow">SEDIAKAN LATIHAN</span><h1>Pilih apa yang nak belajar</h1><p>Kategori visual, topik jelas dan terus mula.</p></section>
    <section class="chooser-block"><div class="step-title"><span>1</span><div><b>Pilih tahap</b><small>Pra Sekolah hingga Tahun 6</small></div></div><div class="level-row">${C.levels.map(l=>`<button class="level-card ${p.level===l.id?'active':''}" data-level="${l.id}"><span>${l.emoji}</span><b>${l.short}</b><small>${l.name}</small></button>`).join('')}</div></section>
    <section class="chooser-block"><div class="step-title"><span>2</span><div><b>Pilih kategori</b><small>Warna berbeza untuk mudahkan budak cam subjek</small></div></div><div class="category-subject-grid">${subs.map(s=>{const info=E.packInfo(p.level,s.id),count=s.id==='math'?'Variasi dinamik':`${(info?.count||0).toLocaleString('ms-MY')} item`;return `<button class="category-subject subject-bg-${s.id} ${p.subject===s.id?'active':''}" data-subject="${s.id}"><span class="subject-icon subject-${s.id}">${s.emoji}</span><div><b>${esc(s.name)}</b><small>${esc(subjectDesc(s.id))}</small><em>${count}</em></div><strong>✓</strong></button>`}).join('')}</div></section>
    <section class="chooser-block"><div class="step-title"><span>3</span><div><b>Pilih corak soalan / topik</b><small>Boleh campur semua topik</small></div></div><div class="topic-pattern-grid">${topics.map((t,i)=>`<button class="topic-pattern p${i%6} ${p.topic===t?'active':''}" data-topic="${esc(t)}"><span>${t==='Campur Semua'?'🎲':iconSubject(p.subject)}</span><b>${esc(t)}</b></button>`).join('')}</div></section>
    <section class="chooser-block"><div class="step-title"><span>4</span><div><b>Tetapan latihan</b><small>Pilih mode, kesukaran dan bilangan soalan</small></div></div><div class="mode-grid"><button class="mode-card learn ${p.mode==='learn'?'active':''}" data-mode="learn"><span>💡</span><div><b>Mode Belajar</b><small>Feedback & penerangan terus</small></div></button><button class="mode-card exam ${p.mode==='exam'?'active':''}" data-mode="exam"><span>📝</span><div><b>Mode Ujian</b><small>${+p.level>=4?'Auto ikut agihan aras 5:3:2 bila dipilih':'Semak semua jawapan di akhir'}</small></div></button></div><div class="setup-split"><div><label>Kesukaran ${uasaAuto?'<span class="uasa-pill">5:3:2</span>':''}</label><div class="segmented">${[['auto',+p.level>=4&&p.mode==='exam'?'Auto · UASA':'Auto'],['mudah','Mudah'],['sederhana','Sederhana'],['sukar','Sukar']].map(([id,n])=>`<button data-diff="${id}" class="${p.difficulty===id?'active':''}">${n}</button>`).join('')}</div></div><div><label>Bilangan soalan</label><div class="count-row">${[5,10,20,30].map(n=>`<button data-count="${n}" class="${p.count===n?'active':''}">${n}</button>`).join('')}</div></div></div><button class="start-btn" id="startQuiz">Mula ${p.count} Soalan <span>→</span></button></section>`,'practice');
    document.querySelectorAll('[data-level]').forEach(x=>x.onclick=()=>{setLevel(x.dataset.level);practice()});
    document.querySelectorAll('[data-subject]').forEach(x=>x.onclick=()=>{p.subject=x.dataset.subject;p.topic='Campur Semua';save(true);practice()});
    document.querySelectorAll('[data-topic]').forEach(x=>x.onclick=()=>{p.topic=x.dataset.topic;save(true);practice()});
    document.querySelectorAll('[data-mode]').forEach(x=>x.onclick=()=>{p.mode=x.dataset.mode;save(true);practice()});
    document.querySelectorAll('[data-diff]').forEach(x=>x.onclick=()=>{p.difficulty=x.dataset.diff;save(true);practice()});
    document.querySelectorAll('[data-count]').forEach(x=>x.onclick=()=>{p.count=+x.dataset.count;save(true);practice()});
    document.querySelector('#startQuiz').onclick=startQuiz;
  }

  function startPraActivity(id){
    const a=P.byId(id);state.prefs.level='pra';state.prefs.subject='pra';state.prefs.praActivity=id;save(true);
    if(a.kind==='quiz'){state.prefs.topic=a.topic||'Campur Semua';state.prefs.mode='learn';state.prefs.difficulty='mudah';state.prefs.count=id==='mix'?10:5;save(true);startQuiz();return}
    praRun={id,activity:a};view='praSpecial';renderPraSpecial();
  }
  function praExit(){praRun=null;view='practice';render()}
  function recordPraActivity(topic,score,total,extra={}){
    updateStreak();const xp=Math.max(5,score*5);state.xp+=xp;state.answers+=total;state.correct+=score;const now=new Date();state.sessions.unshift({date:now.toLocaleDateString('ms-MY'),day:dayKey(now),ts:Date.now(),level:'pra',subject:'pra',topic,difficulty:'mudah',mode:'activity',score,total,pct:total?Math.round(score/total*100):100,answers:[],...extra});state.sessions=state.sessions.slice(0,100);save(true);return xp;
  }
  function praDone(title,emoji='🌟',score=1,total=1,extra={}){
    const xp=recordPraActivity(title,score,total,extra);praRun={done:true,title,emoji,xp,score,total};renderPraSpecial();beep(true)
  }
  function renderPraSpecial(){
    if(!praRun)return praExit();
    if(praRun.done){shell(`<section class="pra-done"><div>${praRun.emoji}</div><small>AKTIVITI SELESAI</small><h1>Bagus, ${esc(state.profile.name)}!</h1><p>${esc(praRun.title)} selesai · +${praRun.xp} XP</p><div class="result-actions"><button class="start-btn" id="praAgain">Main Lagi</button><button class="soft-btn large" id="praBack">Pilih Aktiviti</button></div></section>`,'practice');document.querySelector('#praAgain').onclick=()=>startPraActivity(state.prefs.praActivity);document.querySelector('#praBack').onclick=praExit;return}
    const kind=praRun.activity.kind;if(kind==='draw')return renderPraDraw();if(kind==='color')return renderPraColor();if(kind==='memory')return renderPraMemory();if(kind==='listen')return renderPraListen();if(kind==='order')return renderPraOrder();praExit();
  }
  function praShell(title,subtitle,body){shell(`<section class="pra-special-head"><button class="icon-btn" id="praExit">←</button><div><small>PRA SEKOLAH</small><h1>${title}</h1><p>${subtitle}</p></div></section>${body}`,'practice');document.querySelector('#praExit').onclick=praExit}
  function renderPraDraw(){
    const prompt=praRun.prompt||P.drawPrompt();praRun.prompt=prompt;
    praShell('✍️ Lukis & ikut garisan','Gunakan jari atau mouse. Tak ada markah salah — fokus koordinasi tangan.',`<section class="draw-card"><div class="trace-wrap"><div class="trace-target">${esc(prompt)}</div><canvas id="drawCanvas" width="760" height="430"></canvas></div><div class="draw-tools"><div class="draw-colors">${['#173f73','#e84545','#ff9d22','#2fae68','#7957d5'].map((c,i)=>`<button style="--c:${c}" data-draw-color="${c}" class="${i===0?'active':''}"></button>`).join('')}</div><button class="soft-btn" id="clearDraw">Padam</button><button class="start-btn small-start" id="doneDraw">Siap ✓</button></div></section>`);
    const c=document.querySelector('#drawCanvas'),ctx=c.getContext('2d');ctx.lineCap='round';ctx.lineJoin='round';ctx.lineWidth=16;ctx.strokeStyle='#173f73';let drawing=false;
    function pt(e){const r=c.getBoundingClientRect(),x=(e.clientX-r.left)*c.width/r.width,y=(e.clientY-r.top)*c.height/r.height;return[x,y]}
    c.onpointerdown=e=>{drawing=true;c.setPointerCapture(e.pointerId);const[x,y]=pt(e);ctx.beginPath();ctx.moveTo(x,y)};c.onpointermove=e=>{if(!drawing)return;const[x,y]=pt(e);ctx.lineTo(x,y);ctx.stroke()};c.onpointerup=()=>drawing=false;c.onpointercancel=()=>drawing=false;
    document.querySelectorAll('[data-draw-color]').forEach(b=>b.onclick=()=>{ctx.strokeStyle=b.dataset.drawColor;document.querySelectorAll('[data-draw-color]').forEach(x=>x.classList.remove('active'));b.classList.add('active')});document.querySelector('#clearDraw').onclick=()=>ctx.clearRect(0,0,c.width,c.height);document.querySelector('#doneDraw').onclick=()=>praDone('Lukis', '✍️');
  }
  function renderPraColor(){
    praRun.color=praRun.color||'#ff5d73';
    praShell('🎨 Mewarna','Pilih warna, kemudian tekan bahagian gambar yang nak diwarnakan.',`<section class="color-card"><div class="color-scene"><svg viewBox="0 0 700 420" aria-label="Gambar untuk diwarnakan"><rect width="700" height="420" fill="#eaf8ff"/><circle class="paint-region" cx="585" cy="80" r="48" fill="#ffffff" stroke="#425b75" stroke-width="7"/><rect class="paint-region" x="245" y="195" width="220" height="145" rx="8" fill="#ffffff" stroke="#425b75" stroke-width="8"/><polygon class="paint-region" points="220,205 355,105 490,205" fill="#ffffff" stroke="#425b75" stroke-width="8"/><rect class="paint-region" x="330" y="255" width="55" height="85" fill="#ffffff" stroke="#425b75" stroke-width="7"/><rect class="paint-region" x="80" y="230" width="42" height="115" fill="#ffffff" stroke="#425b75" stroke-width="7"/><circle class="paint-region" cx="100" cy="190" r="72" fill="#ffffff" stroke="#425b75" stroke-width="8"/><circle class="paint-region" cx="150" cy="205" r="58" fill="#ffffff" stroke="#425b75" stroke-width="8"/><path d="M0 345 Q150 310 300 350 T700 345 V420 H0Z" fill="#c7efaa" stroke="#6aa85c" stroke-width="5"/></svg></div><div class="palette">${[['#ff5d73','Merah'],['#ffbe2e','Kuning'],['#37b86b','Hijau'],['#3d8df5','Biru'],['#8f62de','Ungu'],['#ff8a32','Jingga'],['#ffffff','Putih']].map(([c,n],i)=>`<button style="--c:${c}" data-paint="${c}" title="${n}" class="${i===0?'active':''}"><span></span><small>${n}</small></button>`).join('')}</div><div class="color-actions"><button class="soft-btn large" id="resetColor">Kosongkan</button><button class="start-btn small-start" id="doneColor">Siap Mewarna ✓</button></div></section>`);
    document.querySelectorAll('[data-paint]').forEach(b=>b.onclick=()=>{praRun.color=b.dataset.paint;document.querySelectorAll('[data-paint]').forEach(x=>x.classList.remove('active'));b.classList.add('active')});document.querySelectorAll('.paint-region').forEach(el=>el.onclick=()=>el.setAttribute('fill',praRun.color));document.querySelector('#resetColor').onclick=()=>document.querySelectorAll('.paint-region').forEach(el=>el.setAttribute('fill','#ffffff'));document.querySelector('#doneColor').onclick=()=>praDone('Mewarna','🎨');
  }
  function renderPraMemory(){
    if(!praRun.deck){praRun.deck=P.memoryDeck(6);praRun.open=[];praRun.matched=[];praRun.moves=0}
    const matched=new Set(praRun.matched),open=new Set(praRun.open);
    praShell('🧠 Memory','Cari dua gambar yang sama. Ingat kedudukan kad!',`<section class="memory-card"><div class="memory-status"><b>${matched.size/2}/6 pasangan</b><span>${praRun.moves} cubaan</span></div><div class="memory-grid">${praRun.deck.map((c,i)=>`<button class="memory-tile ${matched.has(i)?'matched':''} ${open.has(i)?'open':''}" data-memory="${i}" ${matched.has(i)?'disabled':''}><span>${matched.has(i)||open.has(i)?c.emoji:'?'}</span></button>`).join('')}</div></section>`);
    document.querySelectorAll('[data-memory]').forEach(b=>b.onclick=()=>memoryPick(+b.dataset.memory));
  }
  function memoryPick(i){if(praRun.open.includes(i)||praRun.matched.includes(i)||praRun.open.length>=2)return;praRun.open.push(i);renderPraMemory();if(praRun.open.length===2){praRun.moves++;const[a,b]=praRun.open;if(praRun.deck[a].key===praRun.deck[b].key){setTimeout(()=>{praRun.matched.push(a,b);praRun.open=[];if(praRun.matched.length===praRun.deck.length)praDone('Memory','🧠',6,6,{moves:praRun.moves});else renderPraMemory()},450)}else setTimeout(()=>{praRun.open=[];renderPraMemory()},700)}}
  function speakPra(word){if(!('speechSynthesis'in window)){toast(`Dengar: ${word}`);return}speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(word);u.lang='ms-MY';u.rate=.72;speechSynthesis.speak(u)}
  function renderPraListen(){
    if(!praRun.items){praRun.items=P.listenSet(5);praRun.i=0;praRun.score=0;praRun.answered=false}if(praRun.i>=praRun.items.length)return praDone('Pendengaran','👂',praRun.score,praRun.items.length);
    const item=praRun.items[praRun.i];praShell('👂 Pendengaran',`Soalan ${praRun.i+1}/${praRun.items.length} · tekan butang bunyi, kemudian pilih jawapan.`,`<section class="listen-card"><button class="listen-play" id="playWord">🔊<b>Dengar perkataan</b></button><div class="listen-options">${item.choices.map((c,i)=>`<button data-listen="${i}" ${praRun.answered?'disabled':''}>${esc(c)}</button>`).join('')}</div><div id="listenFeedback" class="listen-feedback"></div></section>`);document.querySelector('#playWord').onclick=()=>speakPra(item.say);setTimeout(()=>speakPra(item.say),250);document.querySelectorAll('[data-listen]').forEach(b=>b.onclick=()=>{if(praRun.answered)return;praRun.answered=true;const ok=item.choices[+b.dataset.listen]===item.answer;if(ok)praRun.score++;b.classList.add(ok?'correct':'wrong');document.querySelector('#listenFeedback').innerHTML=`<b>${ok?'✅ Betul!':'❌ Jawapan: '+esc(item.answer)}</b><button class="next-btn" id="nextListen">Seterusnya →</button>`;document.querySelector('#nextListen').onclick=()=>{praRun.i++;praRun.answered=false;renderPraListen()};beep(ok)})
  }
  function renderPraOrder(){
    if(!praRun.round){praRun.round=P.orderRound();praRun.roundNo=praRun.roundNo||1;praRun.score=praRun.score||0;praRun.picked=[]}if(praRun.roundNo>5)return praDone('Susun nombor','↕️',praRun.score,5);
    const r=praRun.round;praShell('↕️ Susun nombor',`Pusingan ${praRun.roundNo}/5 · tekan nombor daripada paling kecil ke paling besar.`,`<section class="order-card"><div class="order-picked">${praRun.picked.length?praRun.picked.map(n=>`<span>${n}</span>`).join('<i>→</i>'):'<small>Mula dengan nombor paling kecil</small>'}</div><div class="order-options">${r.choices.map(n=>`<button data-order="${n}" ${praRun.picked.includes(n)?'disabled':''}>${n}</button>`).join('')}</div><div class="order-help" id="orderHelp"></div></section>`);document.querySelectorAll('[data-order]').forEach(b=>b.onclick=()=>orderPick(+b.dataset.order));
  }
  function orderPick(n){const expected=praRun.round.target[praRun.picked.length];if(n!==expected){const h=document.querySelector('#orderHelp');h.textContent='Cuba lagi — cari nombor yang lebih kecil 😊';h.classList.add('bad');beep(false);return}praRun.picked.push(n);beep(true);if(praRun.picked.length===praRun.round.target.length){praRun.score++;setTimeout(()=>{praRun.roundNo++;praRun.round=praRun.roundNo<=5?P.orderRound():null;praRun.picked=[];renderPraOrder()},500)}else renderPraOrder()}


  async function startQuiz(){
    updateStreak();const p=state.prefs;showLoading('Sediakan latihan…',p.subject==='math'?'Menjana set Matematik baharu.':'Memuatkan bank soalan.');
    try{const diff=(p.mode==='exam'&&+p.level>=4&&p.difficulty==='auto')?'uasa':p.difficulty;const items=await E.makeSet(p.level,p.subject,p.topic,p.count,diff);quiz={items,i:0,score:0,selected:null,answers:[],started:Date.now(),remaining:p.count*45};view='quiz';persistActiveQuiz();hideLoading();renderQuiz();if(state.settings.timer)startTimer()}
    catch(err){hideLoading();toast(err.message||'Gagal memuatkan soalan.');console.error(err)}
  }
  function persistActiveQuiz(){state.activeQuiz=quiz?clone(quiz):null;save(true)}
  function resumeSavedQuiz(){if(!activeQuizResume())return;quiz=clone(state.activeQuiz);view='quiz';renderQuiz();if(state.settings.timer)startTimer()}
  function startTimer(){clearInterval(timerInt);timerInt=setInterval(()=>{if(!quiz)return clearInterval(timerInt);quiz.remaining--;persistActiveQuiz();const el=document.querySelector('#timer');if(el){el.textContent=formatTime(quiz.remaining);el.classList.toggle('warn',quiz.remaining<30)}if(quiz.remaining<=0){clearInterval(timerInt);finishQuiz()}},1000)}

  function renderQuiz(){
    const p=state.prefs,item=quiz.items[quiz.i],answered=quiz.selected!==null,isLearn=p.mode==='learn',pct=Math.round((quiz.i)/quiz.items.length*100);
    app.innerHTML=`<main class="quiz-page"><header class="quiz-top"><button class="icon-btn" id="exitQuiz">←</button><div><small>${esc(levelObj().name)}</small><b>${iconSubject(p.subject)} ${esc(C.subjects[p.subject].name)}</b></div><div class="quiz-counter"><span id="timer" class="timer">${state.settings.timer?formatTime(quiz.remaining):`${quiz.i+1}/${quiz.items.length}`}</span></div></header><div class="quiz-progress"><i style="width:${pct}%"></i></div><section class="quiz-card"><div class="quiz-meta"><span>${esc(item.topic)}</span><span>${isLearn?'Mode Belajar':'Mode Ujian'}</span></div><h1>${esc(item.question)}</h1><div class="answer-list">${item.answers.map((a,idx)=>{let cls='';if(answered&&isLearn){if(String(a)===String(item.correct))cls='correct';else if(idx===quiz.selected)cls='wrong';else cls='dim'}return `<button class="answer-btn ${cls}" data-answer="${idx}" ${answered&&isLearn?'disabled':''}><span>${String.fromCharCode(65+idx)}</span><b>${esc(a)}</b>${answered&&isLearn&&String(a)===String(item.correct)?'<em>✓</em>':''}</button>`}).join('')}</div>${answered&&isLearn?`<div class="feedback-box ${String(item.answers[quiz.selected])===String(item.correct)?'good':'bad'}"><b>${String(item.answers[quiz.selected])===String(item.correct)?'✅ Betul!':'❌ Belum tepat'}</b><p>${esc(item.explanation||'')}</p></div><button class="next-btn" id="nextQ">${quiz.i===quiz.items.length-1?'Lihat Keputusan':'Seterusnya →'}</button>`:''}</section></main>`;
    document.querySelector('#exitQuiz').onclick=()=>{persistActiveQuiz();quiz=null;view='home';render();toast('Sesi disimpan. Boleh sambung kemudian.')};
    document.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>answer(+b.dataset.answer));
    document.querySelector('#nextQ')?.addEventListener('click',nextQ);
  }
  function answer(idx){if(quiz.selected!==null&&state.prefs.mode==='learn')return;const item=quiz.items[quiz.i],chosen=item.answers[idx],ok=String(chosen)===String(item.correct);quiz.selected=idx;if(ok)quiz.score++;quiz.answers.push({id:item.id,q:item.question,chosen:String(chosen),correct:String(item.correct),ok,topic:item.topic,subject:state.prefs.subject,explanation:item.explanation});persistActiveQuiz();if(state.prefs.mode==='learn'){beep(ok);renderQuiz()}else nextQ()}
  function nextQ(){if(quiz.i>=quiz.items.length-1)return finishQuiz();quiz.i++;quiz.selected=null;persistActiveQuiz();renderQuiz()}
  function finishQuiz(){
    clearInterval(timerInt);if(!quiz)return;const p=state.prefs,total=quiz.items.length,score=quiz.score,pct=Math.round(score/total*100),xp=score*10+(pct===100?50:0);state.xp+=xp;state.answers+=total;state.correct+=score;const now=new Date();state.sessions.unshift({date:now.toLocaleDateString('ms-MY'),day:dayKey(now),ts:Date.now(),level:p.level,subject:p.subject,topic:p.topic,difficulty:p.difficulty,mode:p.mode,score,total,pct,answers:quiz.answers});state.sessions=state.sessions.slice(0,100);quiz.result={score,total,pct,xp,answers:quiz.answers};state.activeQuiz=null;save(true);view='result';beep(pct>=60);renderResult();
  }
  function renderResult(){
    const r=quiz.result,msg=r.pct===100?'Cemerlang! 🌟':r.pct>=80?'Hebat! 👏':r.pct>=60?'Bagus, teruskan! 💪':'Jom cuba lagi 📚',weak=[...new Set(r.answers.filter(a=>!a.ok).map(a=>a.topic))];
    app.innerHTML=`<main class="result-page"><section class="result-card"><div class="result-icon">${r.pct>=80?'🏆':'🎯'}</div><small>KEPUTUSAN</small><h1>${msg}</h1><div class="result-score">${r.pct}%</div><p>${r.score} betul daripada ${r.total} soalan · +${r.xp} XP</p><div class="result-actions"><button class="start-btn" id="retry">Cuba Set Baru</button><button class="soft-btn large" id="backHome">Balik Utama</button></div></section>${weak.length?`<section class="review-summary"><b>Topik untuk ulang kaji</b><div class="topic-list">${weak.map(w=>`<span class="topic active-soft">${esc(w)}</span>`).join('')}</div></section>`:''}<section class="answer-review"><div class="section-title"><div><small>SEMAKAN</small><h2>Jawapan anda</h2></div></div>${r.answers.map((a,i)=>`<div class="review-row ${a.ok?'ok':'no'}"><span>${a.ok?'✓':'!'}</span><div><small>${i+1}. ${esc(a.topic)}</small><b>${esc(a.q)}</b><p>Jawapan anda: ${esc(a.chosen)}${a.ok?'':` · Betul: ${esc(a.correct)}`}</p>${!a.ok?`<em>${esc(a.explanation||'')}</em>`:''}</div></div>`).join('')}</section>${nav('progress')}</main>`;
    bindCommon();document.querySelector('#retry').onclick=startQuiz;document.querySelector('#backHome').onclick=()=>{quiz=null;view='home';render()};
  }

  function progress(){
    const sessions=state.sessions,pct=state.answers?Math.round(state.correct/state.answers*100):0,bySubject={};sessions.forEach(s=>{bySubject[s.subject]??={n:0,c:0,t:0};bySubject[s.subject].n++;bySubject[s.subject].c+=s.score;bySubject[s.subject].t+=s.total});
    const wrongTopics={};sessions.forEach(s=>(s.answers||[]).filter(a=>!a.ok).forEach(a=>{const key=`${s.subject}|${a.topic}`;wrongTopics[key]=(wrongTopics[key]||0)+1}));const weak=Object.entries(wrongTopics).sort((a,b)=>b[1]-a[1]).slice(0,6);
    shell(`<section class="practice-header"><span class="eyebrow">PRESTASI ${esc(state.profile.name).toUpperCase()}</span><h1>Progress pembelajaran</h1><p>Nampak terus apa yang dah kuat dan topik mana patut ulang.</p></section><section class="stats-row wide"><div class="metric-card"><span>🎯</span><div><small>Ketepatan keseluruhan</small><b>${pct}%</b></div></div><div class="metric-card"><span>✅</span><div><small>Jumlah soalan</small><b>${state.answers}</b></div></div><div class="metric-card"><span>📚</span><div><small>Jumlah sesi</small><b>${sessions.length}</b></div></div></section>
    <section class="content-section"><div class="section-title"><div><small>SUBJEK</small><h2>Prestasi mengikut subjek</h2></div></div>${Object.keys(bySubject).length?`<div class="performance-grid">${Object.entries(bySubject).map(([id,v])=>{const p=Math.round(v.c/v.t*100);return `<div class="performance-card"><span class="subject-icon subject-${id}">${iconSubject(id)}</span><div><b>${esc(C.subjects[id]?.name)}</b><small>${v.n} sesi · ${p}% tepat</small><i><em style="width:${p}%"></em></i></div><strong>${p}%</strong></div>`}).join('')}</div>`:`<div class="empty-card">Belum ada rekod. Buat satu latihan dulu 😊</div>`}</section>
    <section class="content-section"><div class="section-title"><div><small>FOKUS</small><h2>Topik perlu ulang</h2></div></div><div class="focus-card">${weak.length?weak.map(([key,n])=>{const [sub,topic]=key.split('|');return `<div class="focus-row"><span class="subject-icon subject-${sub}">${iconSubject(sub)}</span><div><b>${esc(topic)}</b><small>${esc(C.subjects[sub]?.name)} · tersalah ${n} kali</small></div><strong>Ulang</strong></div>`}).join(''):'<div class="empty-inline">Belum cukup data untuk kenal pasti topik lemah.</div>'}</div></section>
    <section class="content-section"><div class="section-title"><div><small>SEJARAH</small><h2>Latihan terkini</h2></div></div><div class="history-card">${sessions.length?sessions.slice(0,15).map(s=>`<div class="history-line"><span class="subject-icon subject-${s.subject}">${iconSubject(s.subject)}</span><div><b>${esc(C.subjects[s.subject]?.name)}</b><small>${esc(levelObj(s.level).short)} · ${esc(s.topic)} · ${esc(s.date)}</small></div><strong>${s.pct}%</strong></div>`).join(''):'<div class="empty-inline">Tiada sesi lagi.</div>'}</div></section>`,'progress');
  }

  async function settings(){
    const downloaded=state.settings.offlineDownloadedAt,bytes=formatBytes(E.totalBytes()),bank=E.totalStatic().toLocaleString('ms-MY');
    shell(`<section class="practice-header"><span class="eyebrow">TETAPAN</span><h1>Profil & aplikasi</h1><p>Semua benda penting, tanpa menu yang berserabut.</p></section><section class="settings-card"><label>Nama pelajar<input id="studentName" class="name-input compact" maxlength="20" value="${esc(state.profile.name)}"></label><div class="avatar-label">Avatar</div><div class="avatar-picker compact">${AVATARS.map(a=>`<button class="avatar-choice ${state.profile.avatar===a?'active':''}" data-avatar-edit="${a}">${a}</button>`).join('')}</div></section>
    <section class="settings-card"><div class="setting-line"><div><b>🔊 Bunyi feedback</b><small>Bunyi ringkas selepas jawab.</small></div><button class="toggle ${state.settings.sound?'on':''}" data-toggle="sound"><i></i></button></div><div class="setting-line"><div><b>⏱️ Timer</b><small>45 saat setiap soalan.</small></div><button class="toggle ${state.settings.timer?'on':''}" data-toggle="timer"><i></i></button></div><div class="setting-line"><div><b>📱 Pasang aplikasi</b><small>Add to Home Screen.</small></div><button class="soft-btn" id="installSettings">Pasang</button></div></section>
    <section class="settings-card"><div class="section-title"><div><small>OFFLINE</small><h2>Bank soalan</h2></div><span>${bank}+ soalan</span></div><p>${formatBytes(E.totalBytes())} data static. ${downloaded?`✅ Pernah download: ${esc(downloaded)}`:'Download semua sekali untuk akses penuh tanpa internet.'}</p><div class="offline-progress hidden" id="offlineProgress"><div><span id="offlineLabel">0 / 40 pek</span><b id="offlinePct">0%</b></div><i><em id="offlineBar" style="width:0%"></em></i></div><div class="setting-buttons"><button class="start-btn small-start" id="downloadAll">Download Semua</button><button class="soft-btn large" id="clearCache">Kosongkan Cache</button></div></section>
    <section class="settings-card"><div class="section-title"><div><small>DATA</small><h2>Backup progress</h2></div></div><p>Progress v9 disimpan dalam localStorage + IndexedDB. Backup berguna kalau tukar phone atau clear browser data.</p><div class="setting-buttons"><button class="soft-btn large" id="backupBtn">⬇ Backup</button><button class="soft-btn large" id="restoreBtn">⬆ Restore</button><button class="danger-btn" id="resetData">Reset Progress</button></div></section>`,'settings');
    document.querySelector('#studentName').onchange=e=>{state.profile.name=e.target.value.trim()||state.profile.name;save(true);settings()};
    document.querySelectorAll('[data-avatar-edit]').forEach(b=>b.onclick=()=>{state.profile.avatar=b.dataset.avatarEdit;save(true);settings()});
    document.querySelectorAll('[data-toggle]').forEach(b=>b.onclick=()=>{state.settings[b.dataset.toggle]=!state.settings[b.dataset.toggle];save(true);settings()});
    document.querySelector('#installSettings').onclick=installApp;document.querySelector('#downloadAll').onclick=downloadAllOffline;document.querySelector('#clearCache').onclick=clearDataCache;document.querySelector('#backupBtn').onclick=exportBackup;document.querySelector('#restoreBtn').onclick=()=>restoreFile.click();
    document.querySelector('#resetData').onclick=()=>{if(confirm('Reset semua progress v9 dan mula semula?')){state=clone(defaults);localStorage.removeItem(STORAGE_KEY);idbSave(state).catch(()=>{});save(true);toast('Progress direset');view='home';render()}};
  }

  function exportBackup(){const payload={app:'LatihKu Study',version:C.version,exportedAt:new Date().toISOString(),state};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`LatihKu-backup-${dayKey()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('Backup siap ✅')}
  restoreFile.onchange=async e=>{const f=e.target.files?.[0];if(!f)return;try{const data=JSON.parse(await f.text());if(!data.state)throw new Error('Fail backup tak sah');if(!confirm('Restore backup ini? Progress semasa akan diganti.'))return;state=migrate(data.state);state.profile.onboarded=!!state.profile.name;save(true);toast('Progress berjaya dipulihkan ✅');view='home';render()}catch(err){toast(err.message||'Backup tak sah')}finally{e.target.value=''}};
  async function downloadAllOffline(){const box=document.querySelector('#offlineProgress'),bar=document.querySelector('#offlineBar'),label=document.querySelector('#offlineLabel'),pct=document.querySelector('#offlinePct'),btn=document.querySelector('#downloadAll');box.classList.remove('hidden');btn.disabled=true;btn.textContent='Downloading…';try{await E.downloadAll((done,total)=>{const p=Math.round(done/total*100);bar.style.width=`${p}%`;label.textContent=`${done} / ${total} pek`;pct.textContent=`${p}%`});state.settings.offlineDownloadedAt=new Date().toLocaleString('ms-MY');save(true);toast('Semua bank soalan siap offline ✅');setTimeout(settings,400)}catch(err){toast(`Download tak lengkap: ${err.message}`);btn.disabled=false;btn.textContent='Cuba Lagi'}}
  async function clearDataCache(){if(!confirm('Kosongkan cache soalan? Progress tak akan dipadam.'))return;E.clearMemory();state.settings.offlineDownloadedAt='';save(true);if('serviceWorker'in navigator){const reg=await navigator.serviceWorker.ready;reg.active?.postMessage({type:'CLEAR_DATA_CACHE'})}toast('Cache dikosongkan');settings()}
  function installApp(){if(installPrompt){installPrompt.prompt();installPrompt.userChoice.finally(()=>installPrompt=null);return}const ios=/iphone|ipad|ipod/i.test(navigator.userAgent);toast(ios?'Safari: Share → Add to Home Screen':'Browser menu → Install app / Add to Home Screen')}
  function bindInstall(){document.querySelector('#installBtn')?.addEventListener('click',installApp)}
  function render(){clearInterval(timerInt);if(!state.profile.onboarded||!state.profile.name)return onboard();if(view==='home')home();else if(view==='practice')practice();else if(view==='praSpecial'&&praRun)renderPraSpecial();else if(view==='progress')progress();else if(view==='settings')settings();else if(view==='quiz'&&quiz)renderQuiz();else home();bindInstall()}
  window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e});window.addEventListener('appinstalled',()=>toast('LatihKu berjaya dipasang 🎉'));window.addEventListener('beforeunload',()=>save(true));document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='hidden')save(true)});if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('sw.js').catch(console.error));
  render();hydrateMirror();
})();
