"""Curated Malay learning facts and Commons search terms (build-time only)."""
# key, Malay name, focused image search, second question answer (category specific)
CATALOG = {
'animals': [
('lion','Singa','intitle:"Panthera leo" male','Darat'),('tiger','Harimau','intitle:"Panthera tigris"','Darat'),('elephant','Gajah','intitle:"Elephas maximus"','Darat'),('giraffe','Zirafah','intitle:Giraffe animal','Darat'),('zebra','Zebra','intitle:"Equus quagga"','Darat'),('panda','Panda','intitle:"Giant panda"','Darat'),('penguin','Penguin','intitle:"Emperor penguin"','Darat dan laut'),('dolphin','Lumba-lumba','intitle:"Bottlenose dolphin"','Laut'),('shark','Jerung','intitle:"Whale shark"','Laut'),('turtle','Penyu','intitle:"Green sea turtle"','Laut'),('frog','Katak','intitle:"Tree frog"','Darat dan air tawar'),('butterfly','Rama-rama','intitle:"Monarch butterfly"','Darat'),('bee','Lebah','intitle:"Apis mellifera" flower','Darat'),('horse','Kuda','intitle:Horse animal','Darat'),('rabbit','Arnab','intitle:"Domestic rabbit"','Darat')],
'food':[
('nasilemak','Nasi lemak','intitle:"Nasi lemak"','Nasi'),('satay','Sate','intitle:Satay','Daging'),('sushi','Sushi','intitle:Sushi plate','Nasi'),('pizza','Pizza','intitle:Pizza margherita','Doh'),('rendang','Rendang','intitle:Rendang','Daging'),('roticanai','Roti canai','intitle:"Roti canai"','Doh'),('laksa','Laksa','intitle:Laksa bowl','Mi'),('spaghetti','Spageti','intitle:"Spaghetti" plate','Pasta'),('burger','Burger','intitle:Hamburger food','Roti'),('croissant','Croissant','intitle:Croissant','Doh'),('dumpling','Ladu','intitle:Jiaozi','Doh'),('taco','Taco','intitle:Tacos food','Tortila'),('pancake','Pankek','intitle:Pancakes','Adunan tepung'),('waffle','Wafel','intitle:Waffle food','Adunan tepung'),('kimchi','Kimchi','intitle:Kimchi','Sayur')],
'produce':[
('apple','Epal','intitle:Apple fruit red','Buah'),('banana','Pisang','intitle:Bananas ripe','Buah'),('orange','Oren','intitle:Orange fruit','Buah'),('watermelon','Tembikai','intitle:Watermelon fruit','Buah'),('pineapple','Nanas','intitle:Pineapple fruit','Buah'),('mango','Mangga','intitle:Mango fruit','Buah'),('durian','Durian','intitle:Durian fruit','Buah'),('kiwi','Kiwi','intitle:Kiwifruit','Buah'),('grape','Anggur','intitle:Grapes fruit','Buah'),('strawberry','Strawberi','intitle:Strawberries fruit','Buah'),('carrot','Lobak merah','intitle:Carrots','Sayur'),('broccoli','Brokoli','intitle:Broccoli','Sayur'),('cabbage','Kubis','intitle:Cabbage vegetable','Sayur'),('eggplant','Terung','intitle:Eggplant fruit','Sayur'),('onion','Bawang','intitle:Onions','Sayur')],
'plants':[
('hibiscus','Bunga raya','intitle:"Hibiscus rosa-sinensis" flower','Bunga'),('rose','Mawar','intitle:Rose flower red','Bunga'),('sunflower','Bunga matahari','intitle:"Helianthus annuus" flower','Bunga'),('orchid','Orkid','intitle:Phalaenopsis flower','Bunga'),('lotus','Teratai','intitle:"Nelumbo nucifera" flower','Bunga'),('jasmine','Melur','intitle:"Jasminum sambac" flower','Bunga'),('tulip','Tulip','intitle:Tulip flower','Bunga'),('lavender','Lavender','intitle:"Lavandula angustifolia"','Bunga'),('coconut','Pokok kelapa','intitle:"Coconut palm"','Pokok'),('bamboo','Buluh','intitle:Bamboo forest','Rumput'),('rice','Padi','intitle:"Rice paddy"','Rumput'),('fern','Paku-pakis','intitle:Fern frond','Paku-pakis'),('cactus','Kaktus','intitle:Cactus plant','Sukulen'),('oak','Pokok oak','intitle:"Oak tree"','Pokok'),('maple','Pokok maple','intitle:"Maple tree"','Pokok')],
'vehicles':[
('car','Kereta','intitle:Toyota Corolla car','Darat'),('bus','Bas','intitle:City bus','Darat'),('truck','Lori','intitle:Truck vehicle','Darat'),('motorcycle','Motosikal','intitle:Motorcycle vehicle','Darat'),('bicycle','Basikal','intitle:Bicycle vehicle','Darat'),('train','Kereta api','intitle:Passenger train','Landasan'),('tram','Trem','intitle:Tram vehicle','Landasan'),('airplane','Kapal terbang','intitle:Airbus A320 aircraft','Udara'),('helicopter','Helikopter','intitle:Helicopter aircraft','Udara'),('sailboat','Bot layar','intitle:Sailboat','Air'),('ship','Kapal','intitle:Cruise ship','Air'),('submarine','Kapal selam','intitle:Submarine vessel','Bawah air'),('ambulance','Ambulans','intitle:Ambulance vehicle','Darat'),('firetruck','Jentera bomba','intitle:Fire engine vehicle','Darat'),('tractor','Traktor','intitle:Tractor vehicle','Darat')],
'music':[
('piano','Piano','intitle:Grand piano','Kekunci'),('guitar','Gitar','intitle:Acoustic guitar','Tali'),('violin','Biola','intitle:Violin instrument','Tali'),('cello','Selo','intitle:Cello instrument','Tali'),('harp','Harp','intitle:Harp instrument','Tali'),('flute','Seruling','intitle:Flute instrument','Tiupan'),('trumpet','Trompet','intitle:Trumpet instrument','Tiupan'),('saxophone','Saksofon','intitle:Alto saxophone','Tiupan'),('clarinet','Klarinet','intitle:Clarinet instrument','Tiupan'),('trombone','Trombon','intitle:Trombone instrument','Tiupan'),('drums','Set dram','intitle:Drum kit','Pukulan'),('tambourine','Tamborin','intitle:Tambourine instrument','Goncangan atau pukulan'),('xylophone','Xilofon','intitle:Xylophone instrument','Pukulan'),('accordion','Akordion','intitle:Accordion instrument','Belos dan kekunci'),('ukulele','Ukulele','intitle:Ukulele instrument','Tali')],
'jobs':[
('doctor','Doktor','intitle:Physician patient examination','Merawat pesakit'),('nurse','Jururawat','intitle:Nurse patient hospital','Menjaga pesakit'),('firefighter','Anggota bomba','intitle:Firefighters fire','Memadam kebakaran'),('police','Polis','intitle:Police officer uniform','Menjaga keselamatan awam'),('teacher','Guru','intitle:Teacher classroom','Mengajar murid'),('farmer','Petani','intitle:Farmer farming','Menanam tanaman'),('chef','Tukang masak','intitle:Chef kitchen','Menyediakan makanan'),('pilot','Juruterbang','intitle:Pilot cockpit','Menerbangkan pesawat'),('dentist','Doktor gigi','intitle:Dentist patient','Merawat gigi'),('veterinarian','Doktor haiwan','intitle:Veterinarian animal','Merawat haiwan'),('mechanic','Mekanik','intitle:Mechanic automobile','Membaiki kenderaan'),('carpenter','Tukang kayu','intitle:Carpenter woodworking','Membina barangan kayu'),('fisherman','Nelayan','intitle:Fisherman fishing','Menangkap ikan'),('photographer','Jurugambar','intitle:Photographer camera','Mengambil gambar'),('scientist','Saintis','intitle:Scientist laboratory','Menjalankan penyelidikan')],
'sports':[
('football','Bola sepak','intitle:Football match','Bola'),('badminton','Badminton','intitle:Badminton match','Raket dan bulu tangkis'),('basketball','Bola keranjang','intitle:Basketball game','Bola dan bakul'),('volleyball','Bola tampar','intitle:Volleyball match','Bola dan jaring'),('tennis','Tenis','intitle:Tennis match','Raket dan bola'),('tabletennis','Ping pong','intitle:Table tennis match','Bet dan bola'),('swimming','Renang','intitle:Swimming freestyle','Kolam renang'),('cycling','Berbasikal','intitle:Road cycling race','Basikal'),('running','Larian','intitle:Running race athletes','Kasut larian'),('golf','Golf','intitle:Golf player','Kayu golf dan bola'),('archery','Memanah','intitle:Archery competition','Busur dan anak panah'),('bowling','Boling','intitle:Ten pin bowling','Bola dan pin'),('rugby','Ragbi','intitle:Rugby match','Bola bujur'),('hockey','Hoki padang','intitle:Field hockey match','Kayu hoki dan bola'),('gymnastics','Gimnastik','intitle:Gymnastics balance beam','Palang imbangan')],
'landmarks':[
('eiffel','Menara Eiffel','intitle:Eiffel Tower','Perancis'),('taj','Taj Mahal','intitle:Taj Mahal','India'),('pyramids','Piramid Giza','intitle:Giza pyramids','Mesir'),('colosseum','Colosseum','intitle:Colosseum Rome','Itali'),('liberty','Patung Liberty','intitle:Statue of Liberty','Amerika Syarikat'),('greatwall','Tembok Besar China','intitle:Great Wall China','China'),('sydney','Sydney Opera House','intitle:Sydney Opera House','Australia'),('burj','Burj Khalifa','intitle:Burj Khalifa','Emiriah Arab Bersatu'),('petra','Petra','intitle:Petra Treasury','Jordan'),('machu','Machu Picchu','intitle:Machu Picchu','Peru'),('bigben','Menara Elizabeth (Big Ben)','intitle:Elizabeth Tower London','United Kingdom'),('angkor','Angkor Wat','intitle:Angkor Wat temple','Kemboja'),('chichen','Chichen Itza','intitle:Chichen Itza pyramid','Mexico'),('christ','Christ the Redeemer','intitle:Christ Redeemer Rio','Brazil'),('petronas','Menara Berkembar Petronas','intitle:Petronas Twin Towers','Malaysia')],
'space':[
('mercury','Utarid','intitle:Mercury planet NASA','Planet paling hampir dengan Matahari'),('venus','Zuhrah','intitle:Venus planet NASA','Planet kedua dari Matahari'),('earth','Bumi','intitle:Blue Marble Earth','Planet tempat manusia tinggal'),('mars','Marikh','intitle:Mars planet NASA','Dikenali sebagai Planet Merah'),('jupiter','Musytari','intitle:Jupiter planet NASA','Planet terbesar dalam Sistem Suria'),('saturn','Zuhal','intitle:Saturn planet NASA','Mempunyai sistem cincin yang jelas'),('uranus','Uranus','intitle:Uranus planet NASA','Planet ketujuh dari Matahari'),('neptune','Neptun','intitle:Neptune planet NASA','Planet kelapan dari Matahari'),('moon','Bulan','intitle:Full Moon','Satelit semula jadi Bumi'),('sun','Matahari','intitle:Sun NASA solar','Bintang paling hampir dengan Bumi'),('rocket','Roket','intitle:Space shuttle launch','Membawa muatan ke angkasa'),('astronaut','Angkasawan','intitle:Astronaut spacewalk','Manusia yang bertugas di angkasa'),('iss','Stesen Angkasa Antarabangsa','intitle:International Space Station NASA','Makmal yang mengorbit Bumi'),('comet','Komet','intitle:Comet Hale Bopp','Objek berais yang boleh membentuk ekor'),('galaxy','Galaksi','intitle:Andromeda galaxy','Kumpulan sangat banyak bintang')],
'body':[
('eye','Mata','intitle:Human eye','Melihat'),('ear','Telinga','intitle:Human ear','Mendengar'),('nose','Hidung','intitle:Human nose','Menghidu'),('tongue','Lidah','intitle:Human tongue','Merasa'),('hand','Tangan','intitle:Human hand','Memegang'),('foot','Kaki','intitle:Human foot','Berjalan'),('heart','Jantung','intitle:Heart anatomy diagram','Mengepam darah'),('lung','Paru-paru','intitle:Lungs diagram','Pertukaran oksigen dan karbon dioksida'),('brain','Otak','intitle:Human brain lateral','Mengawal banyak aktiviti tubuh'),('stomach','Perut','intitle:Stomach anatomy diagram','Membantu menghadam makanan'),('kidney','Buah pinggang','intitle:Kidney anatomy diagram','Menapis darah dan menghasilkan air kencing'),('skeleton','Rangka','intitle:Human skeleton diagram','Menyokong tubuh'),('teeth','Gigi','intitle:Human teeth smile','Mengunyah makanan'),('skin','Kulit','intitle:Human skin hand','Mengesan sentuhan'),('muscle','Otot','intitle:Muscles anatomy diagram','Membantu tubuh bergerak')],
'roads':[
('stop','Berhenti','intitle:Stop sign Malaysia','Berhenti sepenuhnya'),('giveway','Beri laluan','intitle:Give way sign road','Beri laluan kepada trafik utama'),('crossing','Lintasan pejalan kaki','intitle:Pedestrian crossing sign road','Berwaspada terhadap pejalan kaki'),('speed','Had laju','intitle:Speed limit sign 50','Patuhi had laju yang tertera'),('noentry','Dilarang masuk','intitle:No entry sign road','Jangan masuk ke jalan itu'),('parking','Tempat letak kereta','intitle:Parking sign road','Parkir di tempat yang dibenarkan'),('trafficlight','Lampu isyarat','intitle:Traffic lights red','Berhenti ketika lampu merah'),('railway','Lintasan kereta api','intitle:Railway crossing sign','Berhati-hati sebelum melintas landasan'),('roadworks','Kerja jalan','intitle:Road works sign','Perlahankan kenderaan'),('school','Kawasan sekolah','intitle:School zone sign','Perlahankan kenderaan dan awasi kanak-kanak'),('bend','Selekoh','intitle:Curve warning sign road','Perlahankan kenderaan sebelum selekoh'),('slippery','Jalan licin','intitle:Slippery road sign','Kurangkan laju dan elakkan brek mengejut'),('roundabout','Bulatan','intitle:Roundabout sign road','Beri laluan mengikut peraturan bulatan'),('nopedestrian','Pejalan kaki dilarang','intitle:No pedestrians sign','Jangan berjalan di kawasan itu'),('bicyclelane','Laluan basikal','intitle:Cycle lane sign','Gunakan laluan yang ditetapkan')]
}
STATES=[('Johor','Johor Bahru'),('Kedah','Alor Setar'),('Kelantan','Kota Bharu'),('Melaka','Bandar Melaka'),('Negeri Sembilan','Seremban'),('Pahang','Kuantan'),('Perak','Ipoh'),('Perlis','Kangar'),('Pulau Pinang','George Town'),('Sabah','Kota Kinabalu'),('Sarawak','Kuching'),('Selangor','Shah Alam'),('Terengganu','Kuala Terengganu')]
